### ISSUE TITLE
Error reported by WP 5.2 error detection

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1010]
### Reproduction Steps

Error reported by WP 5.2 error detection and sent via email

This was encountered on a LifterLMS 30-day demo trial site.

I don't know exactly how to recreate but wanted to record the error

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Error Details
=============
An error of type E_ERROR was caused in line 69 of the file /srv/users/denim-butterfly/apps/denim-butterfly/public/wp-content/plugins/lifterlms/includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php. Error message: Uncaught Error: Call to a member function get_enrollment_status() on bool in /srv/users/denim-butterfly/apps/denim-butterfly/public/wp-content/plugins/lifterlms/includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php:69
Stack trace:
#0 /srv/users/denim-butterfly/apps/denim-butterfly/public/wp-admin/includes/template.php(1343): LLMS_Meta_Box_Order_Enrollment->output(Object(WP_Post), Array)
#1 /srv/users/denim-butterfly/apps/denim-butterfly/public/wp-admin/edit-form-advanced.php(670): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#2 /srv/users/denim-butterfly/apps/denim-butterfly/public/wp-admin/post.php(198): include('/srv/users/deni...')
#3 {main}
thrown 
```

### System Information

<details>
<summary>System Report</summary>
WP 5.3.2
LifterLMS 3.37.8
```
<!-- Paste your System Report below this line -->

```

</details>

**Comment by eri-trabiccolo** [comment]
I remember we had another issue like this one.
This happens when you edit an order related to a deleted user.

`An error of type E_ERROR was caused in line 74 of the file /home/{removed}/public_html/wp-content/plugins/lifterlms/includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php. Error message: UncaughtError: Call to a member function get_enrollment_status() on bool in /home/{removed}/public_html/wp-content/plugins/lifterlms/includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php:74Stack trace:#0 /home/{removed}/public_html/wp-admin/includes/template.php(1389): LLMS_Meta_Box_Order_Enrollment->output(Object(WP_Post), Array)#1 /home/{removed}/public_html/wp-admin/edit-form-advanced.php(679): do_meta_boxes(Object(WP_Screen),'side', Object(WP_Post))#2 /home/{removed}/public_html/wp-admin/post.php(206): require('/home/munrocour...')#3 {main}  thrown`

line 74 of includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php as of LifterLMS 4.4.4

HS-136413

**Comment by toyinogun** [comment]
HS-156055
