### ISSUE TITLE
Courses duplicate and disappear on page breaks in student dashboard my courses tab

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1061]
### Reproduction Steps

1. Have the course per page in the LifterLMS Course settings set to create a page break with the number of courses a student is enrolled in. (For this customer it was 9)

2. Have the student enrolled in enough courses to populate at least two pages.

3. Go into the Dashboard My Courses tab and switch between the two pages with the pagination. 

### Expected Behavior

The courses will show the first nine the user is enrolled in and the second page will show the rest. 

### Actual Behavior
Instead, the behavior we see is the last two courses from the first page are also listed on the second page and one of the courses that should be on the second page is not listed.

### System Information

<details>
<summary>System Report</summary>
  
```
LifterLMS
User Switching
Twenty Twenty - Theme
```

</details>

HS-108103
I could recreate this on the staging site. Note in ticket.

**Comment by eri-trabiccolo** [comment]
I think it depends on the fact that by default we order by `menu_order` which in most of the cases it's `0` for all the courses (I think no-one sets this wp value :D) so that param alone can be a good orderby clause when having pagination.

This looks exactly like the following (solved) issue:
https://github.com/gocodebox/lifterlms/issues/853

We can adopt the same approach.
