### ISSUE TITLE
Courses not added to groups

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1068]
### Reproduction Steps

On the Admin Dashboard, click on groups.
Select the group or add a new one.
Select the course you want to add to the group and click on save.
It acts like it's saved but when you come back to the settings page, the course is gone.
Memberships can be added and work just fine but not for courses
This makes sure no course is added to the group.
Here is a link to a short video: https://www.loom.com/share/5242de3970da4d03a99dbbb036c69a0c

HS-114848

### Expected Behavior

The page is meant to refresh and show that the course has been added. 
Also, a notification to show the membership or course has been added would be great. At the moment, no notification for either memberships or courses added to the group.

### Actual Behavior

When adding a course, it doesn't get added to the group but membership gets added easily.

### Error Messages / Logs

None
```
<!-- Paste error logs / backtraces below this line -->

```

### System Information

<details>
<summary>System Report</summary>
  
```
<!-- Paste your System Report below this line -->

```

</details>

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
Hi @toyinogunseinde 
thanks!
This, more than an issue with courses, seems to be an issue with that specific course - specifically with the fact that that course has a `'` in the title. Did you already try with another course?
If I'm right then this is a known issue (happens with other special chars too, like `&`, `-` etc.) which is going to be fixed in the next groups addon release (which as you know it's still in beta).

**Comment by toyinogunseinde** [comment]
Thanks, @eri-trabiccolo. It sure works without the characters as you said. Thanks :)

**Comment by eri-trabiccolo** [comment]
Thanks for reporting @toyinogunseinde 
I'm going to update the groups issue referencing to this one.
