### ISSUE TITLE
Pagination does not work in BuddyBoss default pages

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1077]
### Reproduction Steps

+ Install BuddyBoss Platform -- This is what grants you their members page. (BuddyBoss->Pages->Members) The theme doesn't matter you can set this to a default Twenty-Twenty theme.
+ Go into LifterLMS and make sure the integration is turned on so that our courses page shows up on their Members page.
+ Go into LifterLMS Settings for courses and make sure the number of courses is set to create a break in the number of courses the test user is enrolled in. (For example if your test user is enrolled in 2 courses make sure the courses per page is set to 1)
+ Go to the BuddyBoss members page, select courses, try to use the pagination, it will take you to a 404.

(For comparison you can do this with the WooCommerce integration with no issues when navigating pagination on the my-account/my-courses page.)

### Expected Behavior

+ You should be able to navigate through the multiple pages of courses.

### Actual Behavior

+ A 404 is seen.

For example this is the default url for the members page when looking at courses:
example.local/members/admin/courses/

When you click the 2 page of pagination it changes completely to this:
example.local/dashboard/dashboard/page/2/

If you try to manually add: example.local/members/admin/courses/page/2 it also creates a 404.

Where as this link: example.local/members/admin/courses/courses/page/2 shows the second page. 

### System Information

<details>
<summary>System Report</summary>
  
```
Theme
-------------------------------------------

Name: Astra
Version: 2.3.4
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

BuddyBoss Platform: 1.2.8
LifterLMS: 3.37.16
LifterLMS Helper: 3.0.2
LifterLMS WooCommerce: 2.0.14
WooCommerce: 4.0.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes
WooCommerce: Yes


Template Overrides
-------------------------------------------

```

</details>

HS-115865

**Comment by eri-trabiccolo** [comment]
Summarizing:
- same issue happens with buddypress too, of course, since the bp and bb kinda share the same core and we add our "endpoints" to the buddypress(boss) profile page using the buddypress hooks api
- the issue happens because we display our dashboard templates inside the buddypress profile page content AND we use to filter the paginate links there:
https://github.com/gocodebox/lifterlms/blob/3.37.16/includes/functions/llms.functions.templates.dashboard.php#L854
this is something we shouldn't do (as we actually don't do with WooCommerce, we use [this filter hook](https://github.com/gocodebox/lifterlms/blob/3.37.16/includes/functions/llms.functions.templates.dashboard.php#L866) in our woocommerce integration), or do differently.
- Given the bullet above, the issue seems to be pretty easy to fix, although, as Natalie said, the `paginate_links()` function will generate something like `example.local/members/admin/courses/page/2` when in the course tab of the bp profile page, BUT the actual working URL is `example.local/members/admin/courses/courses/page/2` which reflects the bp nav hierarchy as the "courses" nav item is a sub-nav item of the main nav item "courses":
![Schermata 2020-04-02 alle 18 52 55](https://user-images.githubusercontent.com/7689242/78276483-63f43a80-7513-11ea-928a-d3c1e778889b.png)
so the working URL follows this structure `{bp_members_page}/{user}/{main_nav_slug}/{subnav_slug}`.

I'm struggling on how to tell buddypress to allow pagination for that "main" nav item.
If I can't we're forced to alter the pagination link base for the courses to take into account the URL structure I described above.

**Comment by eri-trabiccolo** [comment]
So I've been not able to allow pagination for the "main" nav item pages, I think it's a bp bug/restriction.

I wend with the b-plan, filtering the pagination links so that:
example.local/members/admin/courses/page/2
turns into
example.local/members/admin/courses/courses/page/2
