### ISSUE TITLE
Conflict with IdeaPush Plugin

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1084]
### Reproduction Steps

Install and activate the Plugin [Ideapush](https://wordpress.org/plugins/ideapush/)
Click on any course(backend)
All existing access plans are gone.
https://www.loom.com/share/44c90c92c7874f03827e1d843aee56f5

### Expected Behavior

I believe it shouldn't remove the access plans

### Actual Behavior

Removes the access plans in courses

### Error Messages / Logs

HS-116748

**Comment by thomasplevy** [comment]
Can you open the JS console and check if any errors are reported?

**Comment by toyinogunseinde** [comment]
Yes, I saw some error there
`llms.js:2189 waiting...
llms.js:2189 waiting...
post.php?post=1879&action=edit:1 [DOM] Found 12 elements with non-unique id #_ajax_nonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"01db1caaa8">​
post.php?post=1879&action=edit:1 [DOM] Found 2 elements with non-unique id #lifterlms_meta_nonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"lifterlms_meta_nonce" name=​"lifterlms_meta_nonce" value=​"e72cb76b78">​ <input type=​"hidden" id=​"lifterlms_meta_nonce" name=​"lifterlms_meta_nonce" value=​"e72cb76b78">​
`

**Comment by eri-trabiccolo** [comment]
@thomasplevy && @toyinogunseinde 
the issue depends on the fact that that plugin registers a taxonomy called `status` and that we use a query arg named `status` here:
https://github.com/gocodebox/lifterlms/blob/3.37.16/includes/models/model.llms.product.php#L71

I haven't really looked at this in depth, just followed the thread: the query performed in `LLMS_Product::get_access_plans()` returns an empty array. 

Because the `status` arg produces a taxonomy `query_var`:
 `           [taxonomy] => status`
and a tax query like:
```
    [tax_query] => WP_Tax_Query Object
        (
            [queries] => Array
                (
                    [0] => Array
                        (
                            [taxonomy] => status
                            [terms] => Array
                                (
                                    [0] => publish
                                )

                            [field] => slug
                            [operator] => IN
                            [include_children] => 1
                        )

                )

            [relation] => AND
            [table_aliases:protected] => Array
                (
                )

            [queried_terms] => Array
                (
                    [status] => Array
                        (
                            [terms] => Array
                                (
                                    [0] => publish
                                )

                            [field] => slug
                        )

                )

            [primary_table] => wp_posts
            [primary_id_column] => ID
        )
```

So... the WP_Query arg `status` doesn't exist, basically we always ran that query as if we didn't pass any `post_status` arg (which was our purpose, maybe?), I then propose to just remove the `status` arg. It'll fix the issue.
If we want to use the `post_status` (assuming that was our original purpose) we should test it doesn't introduce any drawbacks.

**Comment by thomasplevy** [comment]
@eri-trabiccolo please test the theory and let me know the results

**Comment by eri-trabiccolo** [comment]
which theory?
Do you meant "It'll fix the issue." ? 
Sorry, it was: "It fixes the issue.". I tested it before writing.

About the `post_status` I've just verified we create access plans as `published` and don't see where we could set their status to anything else.

**Comment by thomasplevy** [comment]
> If we want to use the post_status (assuming that was our original purpose) we should test it doesn't introduce any drawbacks.

It's supposed to be "post_status" and I typoed and never noticed it because there's no reason a plan would ever have any other status. I guess I meant "test if there's any drawbacks" which I can't imagine there being any

I didn't realize you already tested that it works when changing.

If you don't see a problem submit a pr and I'll deploy later today


Thanks

**Comment by thomasplevy** [comment]
@toyinogunseinde please update customer that we've located the source of the issue and we should have it resolved in a release in the next 24 to 48 hours
