### ISSUE TITLE
Course outline not unmarking lessons complete when quiz attempt removed

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1116]
### Reproduction Steps

+ Add the course outline to a course
+ Add a quiz to the course
+ Take the quiz
+ Go into Reporting and remove quiz attempt
+ Clear student reporting cache
+ Go back into the course and look at the syllabus

### Expected Behavior

+ The lesson for the quiz should be marked as incomplete not crossed out

### Actual Behavior

+ it's still crossed out.

HS-118408

**Comment by thomasplevy** [comment]
@eri-trabiccolo do you have some capacity to have a look at this?

**Comment by eri-trabiccolo** [comment]
mmm yeah, I think it should be "easy" because we should be able to unmark the lesson completed if the trigger is the quiz whose attempt we just removed.

**Comment by eri-trabiccolo** [comment]
WIP in https://github.com/eri-trabiccolo/lifterlms/tree/issue/1116, needs more manual tests and brand new unit tests

**Comment by thomasplevy** [comment]
@eri-trabiccolo WIP looks pretty good with a quick review. I saw one area where I think we might want to run the var(s) through `absint()` when adjusting to a strict comparison. Since there's not a lot o existing test coverage here and WP notoriously passes string numeric IDs I get nervous about these areas.

https://github.com/gocodebox/lifterlms/compare/trunk...eri-trabiccolo:issue/1116#diff-256965020cf1b9caf845362de3582d3fR349

I think there may have been one other place where I saw one var through `absint()` and the other wasn't. Maybe you did the research to ensure it was okay though.

The main method in the WIP, `delete()`, is a bit "long" as far as methods go. I know, I know, we have a lot of long methods already but I think this one can benefit from being broken into at least one helper method:

Some kind of helper method like `get_sibling_attempts()` could be used to lookup up attempts *other* than the current attempt. 

Also, I think the logic of that method can be rearranged so that the mark incomplete method doesn't need to be repeated twice in that method.

**Comment by eri-trabiccolo** [comment]
@thomasplevy when deleting a quiz, at the moment, we delete the related quiz attempts with a db query (), but we don't mark the related lesson as incomplete, i think we should as well.
Let me know if you agree and if you think we should integrate that in #1237 or treat it in a different PR.
