### ISSUE TITLE
Bbpress Forums not private

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1132]
### Reproduction Steps

Install Bbpress and activate
Create a forum and attach the forum to a course.

### Expected Behavior

The forum should be accessed by students only enrolled in that course

### Actual Behavior

Anyone with the forum link can access the course(read-only)

HS-119870

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
This is because we now save the attached bb forum id as string (this is an unwanted side effect after the big inputs sanitization youknowhatimean), but still try to retrieve it as integer:
https://github.com/gocodebox/lifterlms/blob/3.38.0/includes/integrations/class.llms.integration.bbpress.php#L232

The values used to be something like:
`a:1:{i:0;i:2299;}`

while now they are like:
`a:1:{i:0;s:4:"2299";}`

So I'd say, let's replace that line with:
`				'%' . sprintf( '%d;', absint( $forum_id ) ) . '%'`
so that we match new and old values, without adding any db update routine, or asking our users to re-save the courses.

And stop saving forum ids as strings?
We save strings because of this:

https://github.com/gocodebox/lifterlms/blob/3.38.0/includes/integrations/class.llms.integration.bbpress.php#L392

`FILTER_SANITIZE_NUMBER_INT` returns a string, we should use `FILTER_VALIDATE_INT` that automatically converts into ints, or cast the value to int after sanitization (e.g. with absint).

Note that we use `FILTER_SANITIZE_NUMBER_INT` in various places, I think we need to verify where a cast to int is needed.

**Comment by thomasplevy** [comment]
@eri-trabiccolo thanks for digging into this. Seems like a reasonable cause for the regression.

Regarding other places where the filter is used could you please open that as a new issue to investigate so we don't lose track of it in this. I don't want to bundle that into this issue.

Also, can you take on the fix since you've already dug into it?

**Comment by eri-trabiccolo** [comment]
@thomasplevy ok, will do that tomorrow, need to better investigate on what's better between FILTER_VALIDATE_INT and the current sanitization + `absint()` .

**Comment by eri-trabiccolo** [comment]
@thomasplevy I was partially wrong, the issue has been introduced only recently:
https://github.com/gocodebox/lifterlms/commit/30cc2696f524ae1f1504d3ae2f422c4d0ced8ceb#diff-87d6397af0c5d22875aac53a3692fb6b

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
While I finishing the PR I had in mind, I realized that we should actually keep on saving forum ids as array of strings. Here's the reason:
If we look at this query LIKE clause:
https://github.com/gocodebox/lifterlms/blob/3.38.0/includes/integrations/class.llms.integration.bbpress.php#L232
`				'%' . sprintf( 'i:%d;', absint( $forum_id ) ) . '%'`

we don't differentiate (and I think we cannot) between the array indexes and the array values - 
in case of values saved as ints we have something like: `a:2:{i:0;i:2299;i:1;i:3333;}`

This might be not important in this very specific case because the issue would happen if you have a forum id that can be confused with an array index. I won't say it's impossible but... given the fact that a wp install comes with at least 2[3] post ids already taken (hello world, sample page[, privacy policy]) you should have, then, at least an array of 4[5] forums attached to a course. But I don't want to introduce a "bad practice" here.

While if we use strings we can change that query to be sure we match ids only, with something like:
`				'%' . sprintf( 's:%d:"%d";', strlen($forum_id), absint( $forum_id ) ) . '%'`

what do you think?

My work on the initial, wrong, PR can be found here:
https://github.com/eri-trabiccolo/lifterlms/tree/issue/1132

I'd say, lets' keep on saving the forum ids as strings, let's change the query as I proposed in the PR because it takes into account the former way to save the forum ids as integers - it doesn't solve the issue outlined in this comment - then, in a near future analyze the code to spot were we need to adopt the new behavior and:
1) create proper db update routines
2) where relevant change the queries.
