### ISSUE TITLE
MySQL 8.0 Incompatibility

### ISSUE THREAD

**Issue by GabrielGallagher** [gocodebox/lifterlms#1178]
This query is incompatible:
SELECT metas.post_id 
			FROM wp_postmeta AS metas
			JOIN wp_posts AS posts on posts.ID = metas.post_id 
			WHERE metas.meta_key = '_llms_bbp_forum_ids'
			AND metas.meta_value REGEXP 'a:[0-9][0-9]*:{(i:[0-9][0-9]*;(i|s:[0-9][0-9]*):\"?[0-9][0-9]*\"?;)*(i:[0-9][0-9]*;(i|s:[0-9][0-9]*):\"?245801\"?;)' 
			AND posts.post_status = 'publish';

A possible alternative:
mysql> SELECT metas.post_id FROM wp_postmeta AS metas JOIN wp_posts AS posts on posts.ID = metas.post_id WHERE metas.meta_key = '_llms_bbp_forum_ids' AND metas.meta_value REGEXP 'a:[0-9][0-9]*:\\{(i:[0-9][0-9]*;(i|s:[0-9][0-9]*):\"?[0-9][0-9]*\"?;)*(i:[0-9][0-9]*;(i|s:[0-9][0-9]*):\"?245801\"?;)' AND posts.post_status = 'publish';

**Comment by thomasplevy** [comment]
@GabrielGallagher could you edit this to include the information we've requested in the bug report template please: https://github.com/gocodebox/lifterlms/issues/new?template=Bug_Report.md

I asked you to post this here instead of in slack because it lets me ask all of those questions in one go instead of asking them one at a time

Thanks!

**Comment by thomasplevy** [comment]
@GabrielGallagher could you at the very least provide me with the error message you're seeing?

**Comment by thomasplevy** [comment]
Error message:

`(HY000/3692): Incorrect description of a {min,max} interval`

Best I can determine this is an escaping issue, an eloquent articulation of the issue (and solution) can be read at https://forum.osticket.com/d/93783-db-error-3692/21
