### ISSUE TITLE
Merge codes button icon uses old logo

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1241]
### Reproduction Steps

+ Login as admin
+ Visit LifterLMS->Settings->Notifications
+ Edit any notification
+ Look at the Merge Codes button

### Expected Behavior

See the "new" logo as the icon

### Actual Behavior

The old icon is visible

### Error Messages / Logs

n/a

### System and Environment Information

LifterLMS 4.1.0

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by imknight** [comment]
does it mean should be using the lifterlms-icon.png ? rather then the lifterlms-rocket-grey.png ?

**Comment by eri-trabiccolo** [comment]
Hi there, probably not as lifterlms-icon.png foreground is white, I think we need another icon, a grey version of lifterlms-icon.png, right @thomasplevy ?

**Comment by thomasplevy** [comment]
Yea, ideally a grey icon like it is now but using the new icon in favor of the old one 

Source icons can be found here: https://gocodebox.github.io/lifterlms-brand/

(I hope it goes without saying that the icon needs to be resized and cropped)

And ideally we won't change the name of the file so that any 3rd parties that *may* be referencing won't run into 404s
