### ISSUE TITLE
LLMS_Abstract_Database_Store extending classes are not defining the `$type` property generating ugly and generic hook names.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1248]
In the abstract class we define the `$type` property as an empty string: https://github.com/gocodebox/lifterlms/blob/4.2.0/includes/abstracts/llms.abstract.database.store.php#L78

Then we rely on the fact it would have been defined in the extending classes when triggering the following action hooks:
https://github.com/gocodebox/lifterlms/blob/4.2.0/includes/abstracts/llms.abstract.database.store.php#L308
https://github.com/gocodebox/lifterlms/blob/4.2.0/includes/abstracts/llms.abstract.database.store.php#L237

But actually the `$type` property is not defined in the following extending classes:
`LLMS_Event`
`LLMS_Quiz_Attempt`
`LLMS_User_Postmeta` 
in core.
`LLMS_SL_Story_Reply` and `LLMS_SL_Story` (social-learning add-on)

While it's correctly defined in 
`LLMS_Assignment_Submission` (assignments add-on)
`LLMS_Group_Invitation` (groups add-on)
`LLMS_REST_API_Key` and `LLMS_REST_Webhook_Data` (rest/core)

**Comment by thomasplevy** [comment]
@eri-trabiccolo working on this now

**Comment by eri-trabiccolo** [comment]
@thomasplevy I think that we should still keep `'llms__created'` and `'llms__updated'` right? because `$type` can still be empty  (e.g. thinking about a 3rd party), or if we want to not allow that, well we should deprecate those hooks... still we can't remove them now, right?

**Comment by thomasplevy** [comment]
@eri-trabiccolo since this is a bug and the documentation states that 3rd parties *should override* I do not think we should keep bug hooks. If a 3rd party created an integration using our abstract and then relies on our bug hooks (which are very clearly bugs if you look at it for even a second) then I'm sorry.

Keeping the bugged hooks meaning we need to *add new buggy-looking hooks* and I just don't think that makes any sense.

I believe fully in backwards compatibility at all costs but this is very clearly a bug that if anyone is relying on should have reported to us in favor of using something that is clearly a bug. And, well, if they thought we intended it to work as a buggy looking hook then I'm sorry... RIght?

The amout of effor to add a second set of hooks to accommodate a bug just seems dumb.

**Comment by thomasplevy** [comment]
I might be wrong and stubborn. Am I wrong? Should we add in a second set of hooks to preserver potential integrations relying on `__` hooks?

**Comment by thomasplevy** [comment]
I'll just leave them in, sigh.

**Comment by thomasplevy** [comment]
This gets complicated to preserve...

If we add events to our objects and want to preserve `__` hooks we have to add a deprecated call to the deprecated hook, eg:

```php

			/**
			 * Fires when a new database record is created.
			 *
			 * The dynamic portion of this hook, `$type`, refers to the record type.
			 *
			 * @since Unknown.
			 *
			 * @param int                          $id  Record ID.
			 * @param LLMS_Abstract_Database_Store $obj Instance of the record object.
			 */
			do_action( "llms_{$this->type}_created", $this->id, $this );

			/**
			 * Deprecated hook resulting from bug.
			 *
			 * @deprecated [version]
			 *
			 * @link https://github.com/gocodebox/lifterlms/issues/1248
			 */
			do_action_deprecated( "llms__created", $this->id, $this );

```

However, if a 3rd party did extend and didn't define an `$type` property, we now call the hook twice. That means we then need to also run a new check to see if the `$type` is defined, only call the deprecated hook if the type *is* defined.

Does this seem like a sensible amount of additional logic to add to add backwards compatibility into a bug fix?

I took this on because I wanted a small bug fix win  and now I'm fixing a bug and also decreasing the code quality so CC is going to yell at me when I submit a PR for this... sigh.

**Comment by thomasplevy** [comment]
```php
			if ( $this->type ) {

				/**
				 * Fires when a new database record is created.
				 *
				 * The dynamic portion of this hook, `$type`, refers to the record type.
				 *
				 * @since Unknown.
				 *
				 * @param int                          $id  Record ID.
				 * @param LLMS_Abstract_Database_Store $obj Instance of the record object.
				 */
				do_action( "llms_{$this->type}_created", $this->id, $this );

			}

			/**
			 * Deprecated hook resulting from bug.
			 *
			 * @deprecated [version]
			 *
			 * @link https://github.com/gocodebox/lifterlms/issues/1248
			 */
			do_action_deprecated( "llms__created", $this->id, $this );
```

I think this is what we need to do...

**Comment by eri-trabiccolo** [comment]
yeah <3

that is an easy win afterall!
