### ISSUE TITLE
Pagination breaks for [lifterlms_courses] shortcode when embedded on homepage

### ISSUE THREAD

**Issue by zackkatz** [gocodebox/lifterlms#1258]
I know embedding things on the homepage can cause issues. This is likely one of those times :-)

### Reproduction Steps

- Embed a `[lifterlms_courses]` shortcode on the homepage
- Set it to display a limited # of courses so they will be paginated
- Go to homepage, click on the pagination links and the courses won't update

### Expected Behavior

The courses update based on the page # clicked

### Actual Behavior

The courses remain on page one.

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

You can experience yourself on [the Gravity.guide](https://gravity.guide/) homepage.

**Comment by thomasplevy** [comment]
@zackkatz this is *expected* but not desired behavior. We do not apply custom pagination rules that apply to the homepage. We've *considered* reworking the way permalink rewriting works in general so that our permalink structures apply on both the root (homepage) and everywhere else but it hasn't been something we've ever had any actual issues or reports of people *requiring* so we haven't prioritized a rewrite to accommodate this use case (which occurs only with shortcodes).

If this is a blocker for you please let me know so we can add this to our next sprint, otherwise I'll leave this as pending for update in the vague future when we determine it becomes essential to add these rewrite rules on the homepage.

Thanks

**Comment by zackkatz** [comment]
@thomasplevy Not a blocker. I'll just remove the pagination. I agree with the severity assessment :-)

**Comment by thomasplevy** [comment]
@zackkatz thanks

**Comment by nrherron92** [comment]
HS-149151

**Comment by thomasplevy** [comment]
@nrherron92 just a heads up on this that we don't really have any available development capacity for a minor issue like this in the near future. If you feel we need to *increase the severity* of this bug let me know, otherwise it's staying on the backlog for the forseeable future.

**Comment by eri-trabiccolo** [comment]
The solution could just be turning this:
https://github.com/gocodebox/lifterlms/blob/4.11.0/includes/shortcodes/class.llms.shortcode.courses.php#L156
into this:
```php
			'paged'          => is_front_page() ? get_query_var( 'page' ) : get_query_var( 'paged' ),
```

similar thing should be done with the membership shortcode.
