### ISSUE TITLE
LIFTER GROUPS - the invitation to a groups is case sensitive (BUG)

### ISSUE THREAD

**Issue by kresimirdelac** [gocodebox/lifterlms#1265]
### Reproduction Steps

if you invite someone with Name.Surname@domain.com and that user uses name.surname@domain.com when registering (disparities in email address conventions like these happen a lot in corporate world), the person will not be added to that group after registering.

### Expected Behavior

should not be case sensitive.

### Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Safari
+ macOS Catalina
+

**Comment by thomasplevy** [comment]
@kresimirdelac 

Thanks for reporting this. I've confirmed there is a bug here and I've made a copy of this in our LifterLMS Groups repository. Further progress will be updated there and I'm going to close this issue as it's out of scope for the LifterLMS core repository.

If you require direct follow up about this issue once it's been closed please send an email to help@lifterlms.com and one of us can follow up with you via email when the issue has been resolved. Otherwise keep your eye on the changelog for the update.

Best!
