### ISSUE TITLE
Upgrade LifterLMS Sample Course Import Process

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#1305]
+ [x] Adjust current last step to setup wizard
+ [x] Add new Finish step to setup wizard
+ [x] ~Upgrade import file process to bring course and lesson images in addition to featured images to destination instead of just referencing~ See #1196 
+ [x] Get Import files and add 3 new courses to course import process
+ [x] Strip author information from files
+ [x] ~Replace file in core plugin~ See #1276  

### Adjust current last step

<img width="964" alt="‹_A_LifterLMS_Sandbox_—_WordPress-2" src="https://user-images.githubusercontent.com/12163552/91230728-06e36600-e6fa-11ea-9a84-1fe8b8d0fb38.png">

### Prepare Courses
All 3 courses for import are here: https://free-course-template.myliftersite.com/courses/

### Wizard New Screen Concept

![IMG_1336](https://user-images.githubusercontent.com/12163552/91231316-05666d80-e6fb-11ea-8551-cdf55d7861f3.png)

### Copy for Wizard

Install Sample Courses!

Accelerate your progress by installing a quick LifterLMS training course and useful course templates.

~

LifterLMS Quickstart Course

Learn how to use the most important parts of LifterLMS in less than 30 minutes

~

Free Course Lead Magnet Template

A proven mini course template to help grow your email list and increase enrollments 

~

Course Template

A proven course sales page template and lesson structure for high value online courses

**Comment by thomasplevy** [comment]
@chrisbadgett we have a "problem" to consider here... If we are going to include images as an important part of the importable courses and we wish them to be imported by URL reference then we need to consider the availability of the source of these images.

The sample courses were constructed on the trial site server which is under constant stress and while it is pretty stable, it is not behind a CDN and it isn't designed for high availability. We also need to *make sure we never delete this site* so that the images will always be accessible.

We could

A) copy all the images over to s3, put the bucket behind a cloudfront cdn, and then run a find & replace on the export file before committing it to the repository so that the images will always be accessible regardless of the status of the site.
B) Move the site of the myliftersite.com server to a more "stable" WP install. Setting this up as an application on Pagely would have higher availability as a true production environment and allow us to leverage the built-in CDN.
C) Move these courses to the academy site

Thoughts?

**Comment by thomasplevy** [comment]
@chrisbadgett 

Splitting resources and imports feels like making resources something of a useless screen. I propose we keep import and resources together on the "Finish" screen, like this:

![Screenshot_2020-09-10_16-34-13](https://user-images.githubusercontent.com/1290739/92824626-82dcdf80-f383-11ea-8283-133db06002db.png)

After looking at the screencap I think the headlines should not both have exclamation points

Maybe the first headline should say "Resources" instead of "Setup Complete!"

Thoughts?

**Comment by chrisbadgett** [comment]
C) Academy Site. 

As a side note, the updated Quickstart Course is already on the Academy site. 

Also I have updated the theme link we discussed in both the Sandbox and Academy versions of the Quickstart Course.

**Comment by chrisbadgett** [comment]
The consolidation of  the last screens is great.

Last Screen 2 Headings modification:

### Initial Setup Complete...

### Install Sample Courses!

Change "Course Template" title of 3rd course to "Signature Course Template" so the course title bumps to 2 rows for visual alignment.

Extend the width or remove padding of the 3 course featured images to the width of the text container below image so the course image does not appear left & right indented above text body.

**Comment by thomasplevy** [comment]
> Extend the width or remove padding of the 3 course featured images to the width of the text container below image so the course image does not appear left & right indented above text body.

@chrisbadgett this is intentional padding that makes sense when you can actually interact with the screen. Since these are "buttons" they "depress" like a button when selected. All 3 are selected right now (and depressed)

![Peek 2020-09-14 09-11](https://user-images.githubusercontent.com/1290739/93110562-59190680-f66a-11ea-8295-67db5d4254bb.gif)

**Comment by thomasplevy** [comment]
@chrisbadgett or, alternatively, have the unselected slightly transparent:

![Peek 2020-09-14 09-20](https://user-images.githubusercontent.com/1290739/93111577-aea1e300-f66b-11ea-9f6d-c0bdbc458c5d.gif)

**Comment by thomasplevy** [comment]
@chrisbadgett 

> Change "Course Template" title of 3rd course to "Signature Course Template" so the course title bumps to 2 rows for visual alignment.

Titles are pulled via an API (now). Update the title on the site if you'd like the this reflected

**Comment by chrisbadgett** [comment]
I prefer the unselected slightly transparent
