### ISSUE TITLE
[wp-admin] List courses: Mine always shows zero, click it go to list of Posts instead of Courses

### ISSUE THREAD

**Issue by nhandl3** [gocodebox/lifterlms#1365]
### Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced

1. Setup just another WordPress.
2. Install LifterLMS plugin.
3. Create a sample course.
4. In Admin Dashboard, go to Courses > Courses to view list of courses.

+ Include screenshots where applicable
![image](https://user-images.githubusercontent.com/1247539/95416748-8d2bd280-095d-11eb-9927-87f8dac18c75.png)

### Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)

"Mine" should be 1.
Click to "Mine" should stay til in Courses > Courses.

### Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)

"Mine" is 0.
Click "Mine" jump to Posts > All Posts.

### System and Environment Information

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
Hello @nhandl3 
thanks for reporting this.
I've been able to reproduce it following the steps you provided.

This issue has been introduced here:
https://github.com/gocodebox/lifterlms/commit/0eb0be295fc73c3977c83cfb4e6e15d931444f9e#diff-e19958bbb00a71ef76221e7c7686e4c3L80-R94

so it instead of:
`$post_type       = llms_filter_input( INPUT_POST, 'post_type', FILTER_SANITIZE_STRING );
`
we should have:
`$post_type       = llms_filter_input( INPUT_GET, 'post_type', FILTER_SANITIZE_STRING );`
