### ISSUE TITLE
Bugged method in class.llms.controller.quizzes.php which should be deprecated because unused/replaced

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1470]
We don't use the method in the above filename anymore and it should be deprecated.

HS-145671

**Comment by eri-trabiccolo** [comment]
The main problem of that method is that, if used, might create a fatal:

`Uncaught Error: Call to a member function get_key() on boolean in /home/{removed}/public_html/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.quizzes.php:97`

That's because actually we assign a boolean to the `$attempt` variable:
https://github.com/gocodebox/lifterlms/blob/4.10.1/includes/controllers/class.llms.controller.quizzes.php#L89

I think we should fix this (it's a simple fix), and mark it as deprecated (replaced by `LLMS_AJAX_Handler::quiz_start( $request )`).

**Comment by thomasplevy** [comment]
What method?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
https://github.com/gocodebox/lifterlms/blob/4.10.1/includes/controllers/class.llms.controller.quizzes.php#L73

**Comment by thomasplevy** [comment]
I'm really confused by this whole conversation...

**Comment by eri-trabiccolo** [comment]
ahaha.
Because the matter is confused.

There's this method here:
https://github.com/gocodebox/lifterlms/blob/4.10.1/includes/controllers/class.llms.controller.quizzes.php#L73
We don't use it anymore, but it's there, I think it should be deprecated as we use `LLMS_AJAX_Handler::quiz_start( $request )` to start a quiz via ajax.

It happened that a customer, dunno why, used that "old" method (which is public), and found a bug in it.

**Comment by thomasplevy** [comment]
@eri-trabiccolo thank you...

So I replaced a method and neglected to mark it deprecated?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
yes, that's what I think it happened.

I cannot find where we use that `take_quiz` (nor that nonce) anywhere in the code.

**Comment by thomasplevy** [comment]
I think you're right... Since the ajax was introduced the last time the controller method was updated my guess is that this is when the change happened. That was a long time ago and I was a lot worse about documenting back then

https://github.com/gocodebox/lifterlms/blob/trunk/CHANGELOG.md#v390---2017-06-02
