### ISSUE TITLE
Calling `wp_nav_menu()` before `init` (10) hook raises a fatal

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1487]
### Reproduction Steps
This is a simplified way to reproduce it. See the section Related User Information for the real case bug reporting.

+ Make sure you have at least one menu created
+ Execute this code:
```php	add_action( 'init', 'wp_nav_menu', 0 );```

### Expected Behavior

+ a nav menu printed at init|0.

### Actual Behavior

+ Fatal error

I just simplified

### Error Messages / Logs

```
PHP Fatal error:  Uncaught Error: Call to undefined function is_lifterlms() in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/class.llms.nav.menus.php:224
```

### System and Environment Information

LifterLMS 4.11.0
WordPress 5.6

## This issue has been recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
https://wordpress.org/support/topic/bug-report-conflict-with-edd-email-templates-and-lifterlms-template-functions/

The user provides in depth information on how this issue occurs on their website and how they fixed it for their specific case.

This very issue could be fixed by checking whether the function exists before using it, yet the issue is more general and maybe we need to think to a more generic approach.

**Comment by thomasplevy** [comment]
@eri-trabiccolo Do we have a quick explanation of why you would ever need to call `wp_nav_menu()` (a method used to output navigation menus on the frontend of a website) prior to init? Realistically I don't see any reason why it would be called anywhere before then since it's an html-generating function.

However... the user did say this was an EDD conflict but there's no system report and I don't fully understand why this would actually be happening given the use-case here... Maybe it's just a "stupid" conflict?

In any event... can we just fix this by running a check to ensure our used function exists here and call it a day?

https://github.com/gocodebox/lifterlms/blob/e8f454345ebe76ac3f71d48e765cdc7d281a66f5/includes/class.llms.nav.menus.php#L223

Eg:

```php
if ( ! function_exists( 'is_lifterlms' ) || ! is_lifterlms() )
```

**Comment by eri-trabiccolo** [comment]
the quick explanation is that the user calls `wp_nav_menu()` from his EDD mail override, so it's custom code.
And the "conflict" is about the fact that, apparently, EDD sends the emails before `init`(?)

> In any event... can we just fix this by running a check to ensure our used function exists here and call it a day?

Sure, as I said above:
_**This very issue could be fixed by checking whether the function exists before using it**, yet the issue is more general and maybe we need to think to a more generic approach._

But I just wanted to ask you if it was the cose to also think about a more generic approach.

I'm with you then.

**Comment by eri-trabiccolo** [comment]
@thomasplevy  ^
