### ISSUE TITLE
Blank page when a course/membership sales page content is set to redirect to a custom URL but no URL is set

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1546]
### Reproduction Steps

+ Create a course or a membership.
+ Set the Sales Page Content to Redirect to Custom URL.
+ Do not set any custom URL.
+ Publish
+ Visit the course/membership as unlogged user.

### Expected Behavior

+ I should see something

### Actual Behavior

+ I see a blank page

### Error Messages / Logs

n/a

### System and Environment Information

```
LifterLMS 4.17.0
WordPress 5.6.2
```

### This issue has been recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-156177

**Comment by thomasplevy** [comment]
I think this method (and it's equivalent in the course model) should include a check to ensure a URL exists (is not empty) from `get_sales_page_url()`:

https://github.com/gocodebox/lifterlms/blob/1cdf3c49910cc2cdf4d3af016781cd2e8f4fc6b9/includes/models/model.llms.membership.php#L306-L317

EG: this should only return true if the current condition is true AND `get_sales_page_url()` is not empty

**Comment by thomasplevy** [comment]
@toyinogunseinde the related ticket is currently assigned to you and we've decided that we're not going to fix this on an immediate timeline (though we've confirmed the bug) as it's simple enough for the user to *put a url in place* instead of using a blank one.

The *fix* for this would prevent a redirect when the field is empty (it would go to the default page instead of the sales page). If the user wishes it to got to a different url, they should enter one. If they don't wish to use a sales page they should disable the setting.

We'll clean this up in a future release to guard against accidental misconfigurations but for the time being we won't be prioritizing this for immediate development. Thanks!
