### ISSUE TITLE
Registration Date in Reporting matches UTC

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1559]
### Reproduction Steps

+ Set timezone in settings to UTC +6 (or whatever time makes local time tomorrow while UTC is still today)
+ Simulate a new student registering
+ Go into _LifterLMS->Settings->Reporting->Click on said student->look for registration date_

### Expected Behavior

+ The registration date should be the next day

### Actual Behavior

+ The registration date is displayed based on UTC instead of local time.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

HS-158540

**Comment by eri-trabiccolo** [comment]
Alright @thomasplevy this is due to the fact that the `'user_registered'` date is saved in the DB (by WordPress) using GMT (`gmdate()`):
https://github.com/WordPress/WordPress/blob/5.7/wp-includes/user.php#L1880

But we display it as if the date contained the timezone offset via `date_i18n`:
https://github.com/gocodebox/lifterlms/blob/4.19.0/includes/models/model.llms.student.php#L1161

We should actually use `wp_date()` that takes care of the wp timezone settings:
https://developer.wordpress.org/reference/functions/wp_date/
introduced in wp 5.3 - we've just bumped our min version so... fine :D

**Comment by thomasplevy** [comment]
@eri-trabiccolo Sounds good. Let's add this to the current backlog to work on in the near future but not ahead of whatever we're currently embroiled in.

**Comment by nrherron92** [comment]
Can I bump this? The user is curious about a fix.

**Comment by thomasplevy** [comment]
@nrherron92 added back to active, we'll work on it within the next 2 weeks
