### ISSUE TITLE
Course Capacity Not Being Respected

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1564]
### Reproduction Steps

+ On the user's staging site create a new course
+ Publish
+ Then go back and set a course capacity 
+ Save
+ Enroll enough students into the course to hit capacity

### Expected Behavior

+ When a new user attempts to register it should block them because capacity is filled.

### Actual Behavior

+ A couple things:
+ 1: If you publish the course _before_ setting the capacity, and then go back and set a capacity later it does not respect it on either mobile or desktop
+ 2: The customer claims that it does not respect the capacity on mobile ever, but neither myself nor Toyin have not been able to replicate this on any course she's made. The only way I replicated the issue was by creating the course and after publishing going back and setting a cap. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.7
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Events Page (#1280) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.19.0
Db Version: 4.19.0
Course Catalog: Course Catalog (#8735) [[removed]/courses/]
Membership Catalog: Membership Catalog (#8736) [[removed]/memberships/]
Student Dashboard: Dashboard (#8738) [[removed]/dashboard/]
Checkout Page: Purchase (#8737) [[removed]/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: date,DESC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: weak
Terms Required: yes
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: hidden
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 2500
Php Max Upload Size: 10 MB
Php Memory Limit: 256M
Php Post Max Size: 10M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 60
Php Version: 7.3.27-9+0~20210227.82+debian9~1.gbpa4a3d6
Software: Apache/2.4.25 (Debian)
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36


Theme
-------------------------------------------

Name: Divi
Version: 4.9.1
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 4.19.0
LifterLMS Customizations: 1.0.0
LifterLMS Helper: 3.1.0
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Stripe Payment Gateway: 5.3.2
User Switching: 1.5.6


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [X] On a staging site
+ [ ] On a production website
+ [X] With only LifterLMS and a default theme

To be clear I cannot replicate this locally or on trial sites. 

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by nrherron92** [comment]
HS-157285

**Comment by thomasplevy** [comment]
@nrherron92 I'm curious if this is the same as https://github.com/gocodebox/private-issues/issues/8

@eri-trabiccolo what do you think?

**Comment by nrherron92** [comment]
@thomasplevy it's similar, but this is before even reaching the checkout page. There's no notice and you can click on enroll, it doesn't hide the pricing table

**Comment by thomasplevy** [comment]
@nrherron92 were you able to recreate this on a sandbox/local site (with/without Divi?) or only on the customer's staging site?

It feels very much like a caching issue to me. I've updated HelpScout because I can't get into the site to debug further and look at potential caching issues.

**Comment by eri-trabiccolo** [comment]
@thomasplevy @nrherron92 
I can only think about a caching issue as well.

**Comment by thomasplevy** [comment]
Alright... I was right. This is a caching issue, however, it's a result of our own cached data.

In 4.12.0 we added some performance improvements around the data related to the number of students in a given course. 

PR #1486 introduced returning cached data (when available) instead of performing a new query every time the number of students is calculated

The data is recalculated in the course data processor, which runs pretty frequently and should keep this data next to real time, except on large active sites where the processing is deferred to avoid complaints of "too many resources" being used to process this data.

The capacity uses the cached data in favor of recalculating it on demand. I believe that this is the *correct* thing to do. EG: we should use cached data here, especially since we're running this on page load for an end user. With a *large and active course* we don't want to have to manaully recalculate the number of students on every single page load. We could change this to not used cached data but in my mind we'd be creating a performance issue in doing so.

The end result shouldn't be any different between mobile and desktop. The data is cached in the WP database on the postmeta table. There's no reason that it should be working different on mobile or desktop. However, there's a time consideration for how this is being tested.

If the tester checks it on mobile first they might not see it if the data hasn't be calculated yet and then refreshing their desktop later they may see what's expected after.

Course data is scheduled to be recalculated immediately following an enrollment (or unenrollment) and it should run pretty quickly thereafter. If there's 500+ students in a course it gets "throttled" to run every 4 hours.

I don't see 500+ students in the course the customer is talking about. The staging site had 4 "stuck" processor batches. I can't say exactly why they got stuck but we built a database tool to clear these stuck batches.

@nrherron92 can you login to the *live* site and see if there are stuck batches there too?

**Comment by nrherron92** [comment]
@thomasplevy I don't see any stuck batches on the live site

**Comment by thomasplevy** [comment]
@nrherron92 alright... well, as of this moment I'm also not seeing the issue on her live site (or the staging site)

@eri-trabiccolo can you have a look at my notes above and help me determine if you think this is something we should be changing or leave it alone.

I'm thinking that the customer can be informed about how this works and we can move on but I'd like to know if either of you disagree with my assessment of the situation

**Comment by eri-trabiccolo** [comment]
This is interesting.
This is a potentially important information that can be not properly set due to various reasons: some issue with wp-cron, some issue with the process itself, throttling (not for this specific customer's course though).
I wonder if we can really rely on something like that... Clearly on courses with tons of students that query is expensive and we just can't run it at each (llms) page load. On the other hand I wonder why we just don't increment/decrement the student number every time an enrollment/unenrollment happens, instead...
Then we could have even a tool that re-calculates the number of students by course (so not for all the courses) if you know they find the count is wrong for whatever reason, or to re-run it on user deletion ecc.
Something to consider for the future development?

**Comment by thomasplevy** [comment]
Possibly... but whether we calculate it the way we calculate it currently or use hooks to increment/decrement as enrollment changes we still put ourselves in a position where the data might not be 100% accurate all the time. When I added this change I thought "we already have the student count, why not cache it here?"

Perhaps we could add an increment/decrement and have the existing processor functionality as a backup check in case it gets out of sync as a result of any number of meddling that could cause an increment/decrement system to return it incorrectly.

I'm not sure I want to build a recalculation tool. I feel it would belong on the course page somewhere and I don't really feel it's something that we *should have to do*. Also, as soon as we build that we're going to get requests to add a custom field to "fake" the number of students in the course. Some themes provide this and I'm philosophically opposed to building a feature that allows users to lie about the number of students in their course.

**Comment by eri-trabiccolo** [comment]
> Possibly... but whether we calculate it the way we calculate it currently or use hooks to increment/decrement as enrollment changes we still put ourselves in a position where the data might not be 100% accurate all the time.

I see what you mean, although I was thinking to remove some obstacles on the path that takes from A (trigger) to B (students count set). Another thing to consider is that we set the 'enrolled_students' when the task is fully completed
https://github.com/gocodebox/lifterlms/blob/4.20.0/includes/processors/class.llms.processor.course.data.php#L464

while we actually have this information even before dispatching the task:
https://github.com/gocodebox/lifterlms/blob/4.20.0/includes/processors/class.llms.processor.course.data.php#L95

If we move the student count save there we don't make it dependent on the batch process, ok it still depends on wp-cron but we removed an obstacle.

> When I added this change I thought "we already have the student count, why not cache it here?"

And it made totally sense. Although the other course data we treat there are just for reporting purposes, while this one is a little bit more important, I think that we can improve something... 

> Perhaps we could add an increment/decrement and have the existing processor functionality as a backup check in case it gets out of sync as a result of any number of meddling that could cause an increment/decrement system to return it incorrectly.

Yeah...

> I'm not sure I want to build a recalculation tool. I feel it would belong on the course page somewhere and I don't really feel it's something that we should have to do. Also, as soon as we build that we're going to get requests to add a custom field to "fake" the number of students in the course. Some themes provide this and I'm philosophically opposed to building a feature that allows users to lie about the number of students in their course.

I see, makes sense.

**Comment by thomasplevy** [comment]
@nrherron92 while we argue about what to do here can you provide a status update to the user letting them know what we've found and that -- in general -- this really shouldn't be a problem unless WP Cron is not running properly -- which as far as I can tell it seems to be on the production site (but is not running as well on staging, which is pretty normal since WP CRON works based on user requests)

**Comment by nrherron92** [comment]
@thomasplevy yeah I can do that!
