### ISSUE TITLE
5.0.0 alpha issues/feedback

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1577]
Feedback / Issues from @eri-trabiccolo that we haven't investigate too thoroughly yet but we're recording here to avoid potential duplicates if any other tests stumble on these issues:

+ [x] 1) radio buttons in the editor look like checkboxes - so squared and with a small border radius, it’s because of our CSS that applies a small border radius to all the fields
+ [x] 2) checkboxes: it’s not possible to remove a default option once set (in the right panel)
+ [x] 3) checkboxes in the right panel look like radio buttons, and they shouldn’t, also you can check only one option by default, and this doesn’t make a lot of sense for checkboxes
+ [x] 4) a numeric field with no limits set doesn’t validate for positive numbers in front after submission, I got an error saying that the value should be less than 0 (sorry I think that was the error I haven’t copied :()
+ [x] 5) I’ve noticed in the DB that the post author is 0 for the default llms_form post types. I think it should be 1.
+ [x] 6) I’ve rapidly submitted a form with checkboxes checked, in the DB, though the checkbox value was empty.
+ [x] 7) When assigning a location to a form, in the “location modal” there are, supposedly, links to the selected product, with the “external link”(open in a new tab) icon, although clicking nothing happens.
+ [x] 8) When you Show keys of the default two options for both radio and checkboxes the "saved values" are empty.
+ [x] 9) Multiple defaults for checkboxes (grouped) are not rendered, only the latest is.

I have to say that I noticed this and noted rapidly because I was actually looking for something else (how the data was saved, retrieved etc) so I might have missed something e.g for the points 4 and 6

**Comment by thomasplevy** [comment]
I'll editorialize that I'm not sure about item 5. Using `1` assumes that the default user is an admin (a good assumption) and that that user exists in the database. Technically it doesn't really matter who the author is and, historically, we (and other plugins) have used `1` as the default author for programmatically created posts... but I'm not sure it really matters. /shrug

**Comment by eri-trabiccolo** [comment]
@thomasplevy I think you're right on this, it shouldn't be `1` but rather the id of the user that "installs the tables", what do you think? Looks just weird to me having this author `0`.

**Comment by thomasplevy** [comment]
> @thomasplevy I think you're right on this, it shouldn't be `1` but rather the id of the user that "installs the tables", what do you think? Looks just weird to me having this author `0`.

This is the right answer, I agree

**Comment by thomasplevy** [comment]
1, 2, & 3 fixed by https://github.com/gocodebox/lifterlms-blocks/pull/86

**Comment by eri-trabiccolo** [comment]
8 still fixed by gocodebox/lifterlms-blocks#86

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
regarding to

> 5) I’ve noticed in the DB that the post author is 0 for the default `llms_form` post types. I think it should be 1.

well we decided that the post author should be the current user that installs the forms. And that's the problem, I mean, that's what is actually happening right now.
See:
https://github.com/gocodebox/lifterlms/blob/5.0.0-alpha.3/includes/class-llms-forms.php#L246
https://developer.wordpress.org/reference/functions/wp_insert_post/

> 'post_author'
(int) The ID of the user who added the post. Default is the current user ID.

So _usually_ this is not a problem because who installs/updates the plugin running the _install_ it does it via the wp dashboard, so is logged in.
What happened in my case was that I updated the plugin manually (file system) and only after that I logged in via wp-login.php. But the thing is that as soon as I landed on that page (wp-login.php) as not logged-in user the form post types were installed with post_author 0. :/
This means that ideally, if there's a logged in user (a subscriber) and someone updates the plugin manually (file system), as soon as that logged in user loads a page the forms are installed with this user as post author.

I guess this _situation_ can even happen more frequently because of the automatic updates... 
So... how can we avoid this? 
I think these posts can be installed as "db update", so we're sure a valid user would do that.
And as part of the wizard for the new installs?

What do you think?

**Comment by thomasplevy** [comment]
Alright... this is probably potentially happening elsewhere too.

I think we should build a utility function in the install class which validates the the current user id (if one exists) is an admin, if it is not an admin or there's no user (auto updates) it should query WP_Users to find the admin with the lowest ID. This will, very likely, be ID 1 but it might not be.

We could also just use ID 1 on the assumption that this is it and then validate that one.

Pseduo code:

```php
$uid = is_user_logged_in() ? get_current_user_id() : 1;
if ( ! user_is_an_admin( $uid ) ) {
   // query for an admin id
} 
return $uid;
```

**Comment by thomasplevy** [comment]
@eri-trabiccolo I think we've close all these now (on various branches and projects) going to close this. If you disagree please reopen
