### ISSUE TITLE
Quotes are slashed when storing post titles via the course builder as a non-admin user

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1623]
### Reproduction Steps

+ Login as an LMS Manager
+ Navigate to the course builder for a new or existing course
+ Create (or edit) a section (or lesson) title and add single and/or double quote characters to the title. For example: `This is "a" 'title' with quotes`
+ Save changes
+ Reload the page

### Expected Behavior

+ The title would display as entered: `This is "a" 'title' with quotes`

### Actual Behavior

+ Slashes are added to "escape" the quotes, resulting in something like: `This is \"a\" \'title\' with quotes`

### Error Messages / Logs

N/A

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

Initially discussed in Slack: https://lifterlms.slack.com/archives/CCESQHE82/p1620315194183900

**Comment by pondermatic** [comment]
#### Troubleshooting notes to myself

When the user is an admin, the `title_save_pre` filter has these callbacks:
* `trim()`
* `wp_targeted_link_rel()`

When the user is a LMS Manager, the `title_save_pre` filter has these callbacks:
* `trim()`
* `wp_targeted_link_rel()`
* `wp_filter_kses()`

[`kses_init()`](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/kses.php#L2142) calls `kses_init_filters()`, which adds the `wp_filter_kses` filter, if the user does **not** have the `unfiltered_html` capability.

**Comment by pondermatic** [comment]
@thomasplevy and @eri-trabiccolo, should we:
1. Add the `unfiltered_html` capability to the[ `lms_manager` role](https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.roles.php#L288)?
2. Temporarily remove the `wp_filter_kses` filter in [`LLMS_Post_Model`](https://github.com/gocodebox/lifterlms/blob/trunk/includes/abstracts/abstract.llms.post.model.php#L1279) **if** the user has the `lms_manager` role?

WordPress [Administrator](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/includes/schema.php#L743) and [Editor](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/includes/schema.php#L768) roles both have the `unfiltered_html` capability.
It seems like adding that capability to the LifterLMS LMS Manager role would be consistent.

**Comment by eri-trabiccolo** [comment]
@pondermatic 
I think this is a symptom, I think that slashes should not be added whether the user has `unfiltered_html` caps or not. This is just not the expected behavior. Do we agree? We would have the same problem with instructors, and with them and the access plans, or rest-api insertions.

The problem, to me, is that as you noticed `wp_filter_kses` (which runs for users who don't have that cap) "add slashes"  here (a):
https://github.com/gocodebox/lifterlms/blob/c719d58f9cf2f0fee1e7318350ddd04795020e93/includes/abstracts/abstract.llms.post.model.php#L1279
And then we add another slash here (b):
https://github.com/gocodebox/lifterlms/blob/c719d58f9cf2f0fee1e7318350ddd04795020e93/includes/abstracts/abstract.llms.post.model.php#L1324 

So here's the thing:
1) when  inserting/updating a post, the post array is expected to be slashed regardless of the user caps, so the slashing in (b) is correct.
2) The slashing in (a), when user has no `unfiltered_html` caps, is useless, because it'll be done in (b).
3) Actually the whole `*_save_pre` filtering is "useless" since those filters will be already fired in `wp_insert_post()` (`sanitize_post()`). This point connects somewhat to [this other issue](https://github.com/gocodebox/lifterlms/issues/1441)
 where we were discussing about stopping scrubbing `post` properties, so I'd add stop **pre-filtering** to that. :D 

Now... my idea is to remove those `*_save_pre` filters tout-court, but... since [this comment](https://github.com/gocodebox/lifterlms/issues/1441#issuecomment-733808183) I think is still valid, I'd say that the bes we can do is, so unslash after prefiltering, something like this:
```php
				switch ( $key ) {

					case 'content':
						/* This is a WordPress core filter */
						$val = stripslashes( apply_filters( 'content_save_pre', addslashes( $val ) ) );
						break;

					case 'excerpt':
						/* This is a WordPress core filter */
						$val = stripslashes( apply_filters( 'excerpt_save_pre', addslashes( $val ) ) );
						break;

					case 'edit_date':
					case 'ping_status':
					case 'comment_status':
					case 'menu_order':
						$llms_post_key = $key;
						break;

					case 'title':
						/* This is a WordPress core filter */
						$val = stripslashes( apply_filters( 'title_save_pre', addslashes( $val ) ) );
						break;
				}
```
Because yes, you'll have the same problem with the "content" too (e.g. a question's content).
Note: the  `addslashes( $val )` is to escape `\` present in the original `$val`, so they're not lost during the process.
It should be fine (I only did a rapid test).

This is what I think. :D

**Comment by thomasplevy** [comment]
I haven't validated all of @eri-trabiccolo's statements but I'm not going to. This seems sound. Write tests, prove it doesn't break anything, close the issue <3
