### ISSUE TITLE
[5.x] Move address "line 2" to it's own line 

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#1625]
Move "address line 2" to it's own line below "address line 1" as that's the expected location.

**Comment by thomasplevy** [comment]
@chrisbadgett Can I have some more information about why this is an important change to make at this point? What's the N on the amount of feedback on this we've had?

Keep in mind that LifterLMS has had address line one and two on the same line since the release of version 3.0 (early 2016).

I cannot remember a single piece of feedback regarding this since then. THat doesn't mean that the behavior is correct but the cost/benefit of changing this seems steep to me knowing that I'll need to rewrite and test quite a bit of code to change this.

Secondly, you can, with a click, switch the layout of the line from "Columns" to "Stacked" if you (the user in this case) is not happy with the default layout.

**Comment by chrisbadgett** [comment]
Feel free to close. Not a large sample size of feedback here and not critical.
