### ISSUE TITLE
[5.x] Remove Preview option if preview unavailable

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#1626]
If I can't Preview a form from a view, should we hide the WordPress preview link?

![Cursor_and_zoom_0_mp4](https://user-images.githubusercontent.com/12163552/117494140-eedb0c00-af41-11eb-883c-0df3e43d8726.png)

I guess technically we can still preview Desktop, Tablet, and Mobile in the editor though.

**Comment by thomasplevy** [comment]
This gets quite complicated and I'm looking into a solution. At this moment we may have to deal with this. I looked into the core APIs that generate this area and the reason for it being blank is that the post type being edited (an `llms_form`) is not publicly visible/accessible (as in there's actually no permalink for the post that allows it to be edited on the frontend).

The link on the sidebar (where the permalink area might display on a page/post) that says "Location: Checkout" with "Checkout" or "Register" being a link to the location of the form is handled using WP core PHP filters to add a permalink to an otherwise permalink-less post type.

That works great there but in the area you're identifying a different bit of logic is used and I have as of yet been able to identify a way to override that logic: it looks at whether or not the post type can be viewed and then determines if there's a permalink to display.

I could just hide the whole area but I do think there's value in allowing the the device previews within the editor itself.

I'll have to experiment with some things to see if there is a way to modify the existing defaults and drop our preview link in it's place. But we may have to either submit a pull request to the gutenberg repo to add a filter that we can use to override the behavior or we'll have to accept this as "The way it is given the circumstances"
