### ISSUE TITLE
[5.x] Update to Code Provided in Documentation

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1637]
### Reproduction Steps

https://lifterlms.com/docs/add-custom-fields-lifterlms-checkout-open-registration/

+ Add this code to either customizer or function.php on 5.0

### Expected Behavior

+ A new field is added to the registration field that can be filled out

### Actual Behavior

+ This field is added but is not recognized as filled in on submission

### Error Messages / Logs

+ I have it on good authority the fix is just to add a 'name' => 'llms_company_name' to this:

```
$company_name = array(			
'columns' => 12,			
'id' => 'llms_company_name',			
'label' => __('Company Name', 'lifterlms'),			
'last_column' => false,			
'required' => true,			
'type' => 'text' );		

array_push($fields, $company_name);

```
so this is maybe just a documentation update?

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [ ] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
It's _possible_ that we need to update our 5.0 code rather than just the documentation, for bc reason.
I think that we could parse the data that arrive through `'lifterlms_get_person_fields'` filter and fill the not set `name` array field with the `id` value.
What do you think @thomasplevy?

**Comment by thomasplevy** [comment]
5.0 should accommodate legacy code, not vice versa and my intention has been that this should take of it:

https://github.com/gocodebox/lifterlms/blob/93bd4ca55232c6788f5fc11ddb1acbe7cc3bd838/includes/forms/class-llms-form-field.php#L40

https://github.com/gocodebox/lifterlms/blob/93bd4ca55232c6788f5fc11ddb1acbe7cc3bd838/includes/forms/class-llms-form-field.php#L618-L622

but you're right @eri-trabiccolo the same parsing that happens at 

https://github.com/gocodebox/lifterlms/blob/93bd4ca55232c6788f5fc11ddb1acbe7cc3bd838/includes/forms/class-llms-forms.php#L406-L407

Should happen on the return of `get_additional_fields()` so that all legacy custom field code doesn't need to be updated in order to continue working



Good catch @nrherron92

**Comment by thomasplevy** [comment]
@eri-trabiccolo I stated yesterday that this was fixed but it is not. I'm going to assign this to you for the moment but if you have too much on your plate punt it back to me <3

This doesn't need to be done right away but I would like it fixed before an RC (2 weeks)
