### ISSUE TITLE
Inserting Japanese language in any endpoint turns gibberish upon saving

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1639]
### Reproduction Steps

Go to LifterLMS >> Settings >> Accounts and change any of the endpoints to a Japanese text like this: コース
Save your changes.
https://www.loom.com/share/dd0914a8ac2d4845a5bb122fba7229f9

### Expected Behavior

It should save as コース 

### Actual Behavior

Upon page reload(after saving), it comes out as gibberish but the URL actually shows コース as shown here:
![image](https://user-images.githubusercontent.com/62220599/119318978-d113e380-bc71-11eb-8f7d-1bd49b5c4751.png)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
N/A

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

HS-167088

**Comment by thomasplevy** [comment]
@toyinogunseinde 

What's happening is the option value is being sanitized to contain only url-safe characters according to logic found in the WP Core.

The "gibberish" is the URL-encoded version of the Japanese characters.

However, these characters are, technically, URL-safe. We implemented sanitization a while back in order to prevent invalid characters from being stored in these URL slugs. Technically what we're seeing here is more a superficial UX bug.

Trace so we don't have to research this again later:

At the moment we're using WP core's `sanitize_title()` [source](https://developer.wordpress.org/reference/functions/sanitize_title/) which calls `sanitize_title_with_dashes()` [source](https://developer.wordpress.org/reference/functions/sanitize_title_with_dashes/) which replaces the characters with the URL-encoded characters via `utf8_uri_encode()` [source](https://developer.wordpress.org/reference/functions/utf8_uri_encode/)

There's really no problem with what we're doing today on the saving side. Perhaps we could update the output of the option to decode the URL on display via php's `urldecode()`.

At the moment I think the best next steps would be relay that this is a visual issue on the admin panel and let the user know we'll improve the interface in a future release.

I'm going to kick this to "future" with the low priority unless anyone feels this requires more immediate attention
