### ISSUE TITLE
[5.x] Migration script

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1652]
The 5.0 update scripts need to be rewritten:

1) An LLMS_Admin_Notice should pop to "welcome" users to LifterLMS 5.0. This will link to the welcome guide blog post that @chrisbadgett is working on (and will publish in tandem with the release of 5.0).
2) ~~Remove unused "legacy" option values from the db: https://github.com/gocodebox/lifterlms/issues/1592 & https://github.com/gocodebox/lifterlms/issues/1593~~ Change legacy options to not be autoloaded

Some of the legacy options are used to setup default values in the forms when created on plugin install. I need to review the order of operations but to ensure these legacy options can be used to generate new defaults (but then never need to be referenced again) we should check if the forms are installed prior to running an update or after. If they're installed after the migration script should include a form installation step and then remove the legacy options after

Text of the welcome notice:

**Welcome to LifterLMS 5.0!** [on it's own line within the notice, bolded so it stands out a bit]

This new version of LifterLMS brings you the power to build and customize your student information forms using a simple point and click interface constructed on top of the WordPress block editor. Customization like the removal of default fields, changing the text of field labels, or reordering fields within a form is all possible without any code or professional help.

[Read more][link to welcome blog post], [read the docs][link to docs category], or [Get started now][link to the forms admin page]!

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
we should document also that reverting a form to default reverts to a default which is the same for everyone.
When migrating to 5.0 MY registration form can be different from YOUR registration form because their composition is a based on legacy options (step 1): it's a merge of a step 0 (defaults) with the legacy options. After changing something to that form, reverting to default won't make the form back to step 1 but to step 0.
I think this is something to highlight.
(otherwise we should keep track of the legacy options somewhere in order to always merge them to the _defaults_)

**Comment by thomasplevy** [comment]
@eri-trabiccolo I hadn't considered this... maybe we should just leave the legacy options alone in that case... I don't know *where* the best place to document this kind of thing would be (putting it inline near the button is cumbersome and confusing). If we write a doc about it it'll be confusing also and no one will read it until it's "too late" -- although if we're being really honest nothing will be seriously damaged by this...

However, if we just leave the legacy options in the database and flip autoload to false that might be simpler...

Thoughts on that?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Sounds good. I was thinking into compact all them in a new `llms_legacy_account_settings` option (not autoloaded as well), and get rid of the originals. But maybe your solution is better also because if someone rollsback to pre 5.0 doesn't lose them, although they will be not autoloaded anymore... Mmm no this rollback scenario is probably worse. I think we need to make clear that If you roll back you loose legacy options, ok? :)

**Comment by thomasplevy** [comment]
@chrisbadgett can you drop the permalink to the (unpublished) release blog post here when you have it please , thanks <3

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm going to put this on your plate to start writing, shouldn't be too hard, I don't think. I've updated the needs based on our conversation

**Comment by eri-trabiccolo** [comment]
@thomasplevy fine for me.
Just a clarification though, you say:
> The 5.0 update scripts need to be rewritten:

Does this mean there's already a script somewhere? I don't seem to able to find it, and there's nothing related, as far as I can see, in the `functions/updates` dir.

Interesting, most of those options were already not automatically loaded:
https://github.com/gocodebox/lifterlms/commit/4ca42a98f1b2e363e45e19f675506d7402ea3dd3#diff-5ed275651e7aa9e1dad2a35f60658d3fdd90d481f34f3fee4570a8ac37451462


So the migration script would look like this:
https://github.com/eri-trabiccolo/lifterlms/commit/6d960adc19aaf29ca522986ef660b65a229b6381

fine, or do you expect a different approach?

What about showing the admin notice when the update is complete?
![Schermata 2021-06-09 alle 17 25 13](https://user-images.githubusercontent.com/7689242/121383502-ccc11900-c947-11eb-875f-2b8665b29c38.png)

https://github.com/eri-trabiccolo/lifterlms/commit/2cb06fb4fddaedd22731ebb932b647770b5923c4

**Comment by thomasplevy** [comment]
Link to the blogpost will be: https://blog.lifterlms.com/5-0/ 

The post is unpublished so it 404s today but it'll be published in tandem with the public release of 5.0
