### ISSUE TITLE
5.0 form translation error

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1700]
### Reproduction Steps

+ HS-170697 -- I'm waiting on system report and logins
+ Have LifterLMS translated pre-5.0 update
+ Update to 5.0 
+ With the switch to the forms some letters get replaced with code

### Expected Behavior

+ translated special letter should remain as roman characters

### Actual Behavior

+ it gets replaced with random numbers

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

-- I'll update this when it comes in

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 Could you request a copy of the translation file the customer is using. In this scenario that's probably more important than anything else so I can recreate and figure out why this is happening (and how to fix it)

**Comment by nrherron92** [comment]
@thomasplevy users' translation files are attached to his ticket now!

**Comment by thomasplevy** [comment]
@nrherron92 the provided files are for the theme (twenty nineteen) and I think the WP core. I need a copy of the LifterLMS translation file.

I'm going to try to just reproduce the issue on my own in the meantime by making a fake translation file to see if I can figure this out

**Comment by thomasplevy** [comment]
Alright, I figured it out... It seems this is an issue that would only occur with reusable blocks created by LifterLMS during installation migration *if* translations (with "special" characters (accents and whatnot)) exist prior to install / upgrade.

I'm pushing a PR to address this... however, existing issues cannot be fixed in any way that I can figure out so affected users will have to use the "Reinstall Forms" tool after upgrading to the patched version or manually fix the bugged blocks.

Hopefully we'll ship this this week.
