### ISSUE TITLE
“Billing Information” is not replaced with “Student Information”

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1774]
### Reproduction Steps

Create an access plan for a course and check the "free" option.
Then visit the purchase link

### Expected Behavior

According to: https://lifterlms.com/docs/checkout-free-access-plans/ "Billing Information" should be replaced with "Student Information"

### Actual Behavior

Stays as "Billing Information"

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
N/A

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment]
@toyinogunseinde do we have a related ticket or did you just notice this ?

I'm not sure the best way to proceed here as this was a change introduced in 5.0 as a result of allowing customization of the name of the form (instead of it being hardcoded). Once that was introduced it removed the hardcoded dynamic switch. A user can change the name of the form to customize the language. 

We didn't build in a way to provide *dynamic* language changes based on the plan (as was included in pre 5.0 releases). WE added a feature and removed a feature.

You can create multiple forms now and assign the free plans to a form with a different name should the language change based on access plan be essential (of course this does require the add-on).

The template could also be customized to output different language.

@gocodebox/engineering anyone else have any thoughts on this?

**Comment by toyinogun** [comment]
@thomasplevy It was a ticket. HS-174390

**Comment by pondermatic** [comment]
Options (in no particular order):
1. Add a checkout form selector in the access plan editor. This would add a way to relate a form to a course. Currently the only way is to to edit the form and add courses in "Manage Location Settings".
2. Add a "free" checkout form that is used when the access plan `is_free` is checked.

**Comment by thomasplevy** [comment]
> 1. Add a checkout form selector in the access plan editor. This would add a way to relate a form to a course. Currently the only way is to to edit the form and add courses in "Manage Location Settings".

See: https://github.com/gocodebox/lifterlms-custom-fields/issues/13

**Comment by eri-trabiccolo** [comment]
What if we add a form custom field, for billing forms, which is "Title for free access plans", which if empty will default to the form title.

**Comment by toyinogun** [comment]
HS-187017
