### ISSUE TITLE
LMS Manager role should allow override of promote_users capability

### ISSUE THREAD

**Issue by yewzy** [gocodebox/lifterlms#1860]
### Reproduction Steps

1. Add the 'promote_users' capability for the LMS Manager role (using the Members plugin by Memberpress).

Expected behavior: LMS Manager should be able to freely set a user to any roles.
Actual behavior: LMS Manager is only able to set a user to either  Instructor, Instructor's Assistant, LMS Manager or Student

If I include the 'promote_users' capability in a separate role, then set a user to both the custom role, and also the LMS Manager role, the LMS Manager role stills limits the user to promote new/current users to only these 4 roles.

**Comment by thomasplevy** [comment]
Hey there @yewzy 

This sounds like an area where we can't exactly *fix* this issue without either creating custom code specifically to resolve this conflict with this plugin or creating new issues within our plugin in order to accommodate another plugin like this.

LifterLMS *intentionally* limits the user roles that can be managed by our custom roles. The functionality of this role (the LMS Manager) is a pesudo-administrator which can manage LMS content and LMS users. If we are to provide the ability for an LMS manager to natively manage *all* users on the site we break our own role's rules.

The problem here is that WordPress does not have a concept like this built into it. The existing WordPress capabilities allow for editing, creating, and deleting users. There is no capability that says "This user can edit a user of this role." Posts have a more robust capabilities system that allow for more complex rules, but users, in this regard, is a bit "rudimentary" (I'm not criticizing I'm just stating the situation).

So, what's happening (I think) with this conflict here is that LifterLMS *already grants* the capabilities to manage users and so does Memberpress (now that you've granted it in the plugin's settings). But LifterLMS also has code to restrict the user roles that can be managed by this role.

In order to resolve this conflict I see two potential solutions:

### Option 1

Leverage one or more filters in LifterLMS to modify (or remove) this behavior to achieve your requirements:

[llms_user_can_manage_user_ignored_roles](https://developer.lifterlms.com/reference/hooks/llms_user_can_manage_user_ignored_roles/)

This filter provides a list of user roles that are outright ignored by this functionality in LifterLMS. You could add `lms_manager` to this list and then the the restrictions we have in place will be ignored and the LMS Manager role will be able to manage all user roles on the site.

[llms_editable_roles](https://developer.lifterlms.com/reference/hooks/llms_editable_roles/)

You can add one or more roles to the list of roles that can be managed by the `lms_manager` roles so that the roles you'd like the LMS Manager role to be able to manage can be managed by the role.

You wouldn't need to use both of the above, choose the one that suits your needs best.

### Option 2 

Create your own custom role that "copies" the existing functionality of the LMS Manager role, but has a different name and ID. The id of "lms_manager" is what imposes the restriction on which users can be edited so after creating this duplicate role you could add the Memberpress capability to this role and be good to go.

This could be done programmatically using the [WP_Roles](https://developer.wordpress.org/reference/classes/wp_roles/) API or you could use a plugin like [User Roles Editor](https://wordpress.org/plugins/user-role-editor/).


Let me know if this helps!

**Comment by thomasplevy** [comment]
@gocodebox/engineering if someone has a free few minutes to review my suggestions and thinking behind this could you weigh in and let @yewzy know if there's something I'm completely missing or let me know if I'm completely wrong and there's a way that's eluding me that would allow us to add compatibility without leveraging specific Memberpress code (filters, roles, etc...) and simultaneously not break LifterLMS on it's own. Thanks!

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Option 1 is the better to me. Because there are various areas where we list users by role, e.g. some reporting screens, or the option to select which role can skip the enrollment.

About this, @yewzy :
> Add the 'promote_users' capability for the LMS Manager role (using the Members plugin by Memberpress)

You don't need this because our `lms_manager` already can `promote_users`, we just limit the other roles he can promote.

Option 1 described by @thomasplevy will help you achieve your goal.

**Comment by thomasplevy** [comment]
@yewzy does this help out at all?

**Comment by yewzy** [comment]
Thanks @thomasplevy for the detailed explanation! Yes, that does indeed makes sense, and I really appreciate you taking the time to explain how the LMS Manager role is designed. I believe that `llms_editable_roles` will work perfectly for my current use case.

**Comment by thomasplevy** [comment]
You're welcome @yewzy !
