### ISSUE TITLE
[6.x] Remove (most) previously deprecated code and record breaking changes 

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1886]
In preparation for the 6.0 release we might as well remove previously deprecated code.

@pondermatic can you start working on removing deprecated code and logging the removed items as changelogs on a branch to merge into dev-600.

**Comment by pondermatic** [comment]
I'd like to remove [`use function LLMS as llms;`](https://github.com/gocodebox/lifterlms/blob/dev-600/lifterlms.php#L55-L61) from `lifterlms.php` and change all of the uses of `LLMS()` in LifterLMS to `llms()`, and eventually in other add-ons. [PHP function names are case-insensitive](https://www.php.net/manual/en/functions.user-defined.php#example-151), so this won't break 3rd party plugins.

**Comment by pondermatic** [comment]
@eri-trabiccolo , `.changelogs/lifterlm-rest.yml` has a typo in the file name. Commit 9c05198c53a6928020424b2e0a5f37ed944bb9a2.

**Comment by eri-trabiccolo** [comment]
@pondermatic thanks, but I don't think the parser cares about that. It's only ugly :)

**Comment by thomasplevy** [comment]
The filename exists only to prevent uniqueness issues. The title/filename doesn't matter at all really and will be deleted once the changelog is created. Sure, we should try to spell stuff right but it hardly matters so long as the content is not misspelled. No need to change anything in this case.

**Comment by pondermatic** [comment]
@gocodebox/engineering, please look at the WIP branch [dev-600-remove-deprecated-code](https://github.com/gocodebox/lifterlms/tree/dev-600-remove-deprecated-code) to make sure that I'm doing this correctly. My brain is fuzzy.

**Comment by thomasplevy** [comment]
@pondermatic open a draft PR and I'll review

**Comment by pondermatic** [comment]
@gocodebox/engineering, Should we leave recently deprecated items in LifterLMS 6.0.0? Maybe leave deprecated items since LifterLMS 5.0.0 released June 22, 2021, alone?

**Comment by thomasplevy** [comment]
@pondermatic Yea, don't remove any upcoming (as of yet unreleased) deprecations in 6.x.

Anything in 5.x can be removed (and I'd like it to be). There's no timeline on the amount of time required to pass between a deprecation and a removal. I would say that 6 months is more than enough.

**Comment by pondermatic** [comment]
@thomasplevy,
[`LLMS_Notifications::dispatch_processors()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/notifications/class.llms.notifications.php#L117) was deprecated in 3.38.0, and is only used in [`LLMS_Notifications::__construct()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/notifications/class.llms.notifications.php#L101) if the `llms_processors_async_dispatching` filter returns false, which none of the LifterLMS projects use. Should we deprecate the `llms_processors_async_dispatching` filter and then remove the deprecated function and filter at a later date?

**Comment by thomasplevy** [comment]
If anyone was using the filter to disable async processing they *would have* been met with the deprecation warning. I suppose what you are suggesting is *technically* the correct way to do this and the filter should have been introduced as deprecated but... I doubt anyones actually using this and if they are they are *already aware* they are using deprecated functionality due to the deprecation notice thrown by the callback.

In this scenario I think we're safe to remove the filter alongside the callback. If you disagree with me strongly then do as you're suggesting and deprecate the filter now.

**Comment by pondermatic** [comment]
Your logic makes sense to me. I had not thought about the warning from the deprecated function. I will remove both the filter and the function.

**Comment by pondermatic** [comment]
@thomasplevy,
While removing the deprecated [`LLMS_Person_Handler::get_available_fields()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.person.handler.php#L544) function, I found calls to it from [LifterLMS ConvertKit](https://github.com/gocodebox/lifterlms-convertkit/blob/trunk/includes/class-llms-integration-convertkit.php#L138) that allow compatibility with LifterLMS < 5.0.

Options:
1. Leave the deprecated function alone for now. Is there a way to nag the user to upgrade LifterLMS?
2. Remove the deprecated function and the compatibility check in LifterLMS ConvertKit.

**Comment by pondermatic** [comment]
I may have found some code that should have been deprecated in 4.4.3 but wasn't.

## [`LLMS_AJAX_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.ajax.handler.php#L1146)
+ calls [`LLMS_Post_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.post.handler.php#L145), which was deprecated in 4.4.3 and has no replacement
+ calls `LLMS_Meta_Box_Course_Outline::lesson_tile()` and I can't find the `LLMS_Meta_Box_Course_Outline` class anywhere
+ is not used anywhere

## [`LLMS_AJAX_Handler::create_section()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.ajax.handler.php#L1082)
+ calls [`LLMS_Post_Handler::create_section()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.post.handler.php#L105), which is not deprecated but probably should be and is not used anywhere else
+ calls `LLMS_Meta_Box_Course_Outline::section_tile()` from the non-existing `LLMS_Meta_Box_Course_Outline` class
+ is not used anywhere

## [`LLMS_AJAX_Handler::add_lesson_to_course()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.ajax.handler.php#L1183)
+ calls [`LLMS_Lesson_Handler::assign_to_course`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.lesson.handler.php#L52), which is not deprecated but possibly should be because it is not called from anywhere else.
+ calls `LLMS_Meta_Box_Course_Outline::lesson_tile()`, which does not exist
+ is not used anywhere

**Comment by thomasplevy** [comment]
Leave it 

> 1. Leave the deprecated function alone for now. Is there a way to nag the user to upgrade LifterLMS?

Leave it for now. I'd love to say drop it and bump version support of CK to 6.0 but that will require a coordinated release. Better to drop it after 6.0 is actually released. That does mean we need to leave a function in the core that we don't want to but that's fine for now.

**Comment by thomasplevy** [comment]
AJAX methods probably should have been deprecated / removed in version 3.x, I'm betting... In any event. I think the semantically correct thing to do is mark them as deprecated now and remove them later. However, knowing that they currently *do not work* since they call methods that do not exist the better thing to do would probably be just to remove them outright since they're broken. If someone actually is using them *they're already encountering fatal errors* so...

The best thing I can come up with right now is to deprecate them on 5.x. We'll do at least one or two more 5.x releases before 6.0 so if we deprecate them there (and basically simultaneously remove them on 6.x) that seems the best strategy to me... Do you have another opinion?

**Comment by pondermatic** [comment]
> The best thing I can come up with right now is to deprecate them on 5.x. We'll do at least one or two more 5.x releases before 6.0 so if we deprecate them there (and basically simultaneously remove them on 6.x) that seems the best strategy to me... Do you have another opinion?

That sounds like a very good idea to me. I didn't know about the timing of another 5.x release before the 6.0 release.

**Comment by pondermatic** [comment]
@thomasplevy, do you want me to run the deprecated [`lifterlms_created_person`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/forms/class-llms-form-handler.php#L455) action hook through `do_action_deprecated()`, or just just remove it? It occurred to me that we should warn developers.

**Comment by pondermatic** [comment]
@thomasplevy, 
The deprecated [`llms_get_minimum_password_strength()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/functions/llms-functions-deprecated.php#L180) function is only used in 
[`LLMS_Frontend_Assets::enqueue_inline_pw_script()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.frontend.assets.php#L142), which is not used anywhere. Should we remove `LLMS_Frontend_Assets::enqueue_inline_pw_script()` as well?

**Comment by pondermatic** [comment]
@thomasplevy, I'm removing the deprecated `wp-background-processing` library directory, which is the last thing in [`includes/libraries`](https://github.com/gocodebox/lifterlms/tree/5.6.0/includes/libraries). Should we remove `includes/libraries` as well?

**Comment by pondermatic** [comment]
@thomasplevy,
The [`llms_get_quiz_theme_setting()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/functions/llms.functions.quiz.php#L151) function is deprecated, but used in [`LLMS_Admin_Builder::get_custom_schemas()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/admin/class.llms.admin.builder.php#L120) and `LLMS_Quiz::toArrayAfter()` to maintain backward compatibility. Do you want me to remove the backward compatibility code in addition to the deprecated function?

**Comment by thomasplevy** [comment]
> @thomasplevy, do you want me to run the deprecated [`lifterlms_created_person`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/forms/class-llms-form-handler.php#L455) action hook through `do_action_deprecated()`, or just just remove it? It occurred to me that we should warn developers.

Use `do_action_deprecated()` for now.

**Comment by thomasplevy** [comment]
> @thomasplevy, I'm removing the deprecated `wp-background-processing` library directory, which is the last thing in [`includes/libraries`](https://github.com/gocodebox/lifterlms/tree/5.6.0/includes/libraries). Should we remove `includes/libraries` as well?

Yes

**Comment by thomasplevy** [comment]
> @thomasplevy, The [`llms_get_quiz_theme_setting()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/functions/llms.functions.quiz.php#L151) function is deprecated, but used in [`LLMS_Admin_Builder::get_custom_schemas()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/admin/class.llms.admin.builder.php#L120) and `LLMS_Quiz::toArrayAfter()` to maintain backward compatibility. Do you want me to remove the backward compatibility code in addition to the deprecated function?

Not yet. We're still using this in the labs plugin as far as I can remebmer

**Comment by pondermatic** [comment]
>>@thomasplevy, do you want me to run the deprecated `lifterlms_created_person` action hook through `do_action_deprecated()`, or just just remove it? It occurred to me that we should warn developers.

>Use `do_action_deprecated()` for now.

`lifterlms_created_person` is also triggered in these add-ons:
- Formidable Forms
- Gravity Forms
- WooCommerce
- WPForms

They also trigger the newer `lifterlms_user_registered` action hook.

Should I leave the add-ons alone, or submit PRs that change `do_action()` to `do_action_deprecated()`?

**Comment by thomasplevy** [comment]
PRs for the add-ons please <3

**Comment by pondermatic** [comment]
@thomasplevy,
While removing the deprecated[ `LLMS_Section::get_order()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.section.php#L273) method, I noticed that the similar [`LLMS_Lesson::get_order()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.lesson.php#L270) was not deprecated. Want me to make it deprecated?

**Comment by pondermatic** [comment]
@thomasplevy, 
While removing the deprecated [`LLMS_Post_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.post.handler.php#L145), I noticed that it is being used by [`LLMS_AJAX_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.ajax.handler.php#L1146), which isn't being used anywhere and would break if it was because `LLMS_Section::count_children_lessons()` was removed in LifterLMS 4.0.0. Should I remove `LLMS_AJAX_Handler::create_lesson()`?

**Comment by thomasplevy** [comment]
> @thomasplevy, While removing the deprecated[ `LLMS_Section::get_order()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.section.php#L273) method, I noticed that the similar [`LLMS_Lesson::get_order()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.lesson.php#L270) was not deprecated. Want me to make it deprecated?

OKay!

**Comment by thomasplevy** [comment]
> @thomasplevy, While removing the deprecated [`LLMS_Post_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.post.handler.php#L145), I noticed that it is being used by [`LLMS_AJAX_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.ajax.handler.php#L1146), which isn't being used anywhere and would break if it was because `LLMS_Section::count_children_lessons()` was removed in LifterLMS 4.0.0. Should I remove `LLMS_AJAX_Handler::create_lesson()`?

This should be handled like the other item above you noticed in this situation. I don't want to *remove something* that will break something that isn't deprecated. So deprecate the other thing and we can remove in 5.x before release (or remove some other time)

**Comment by pondermatic** [comment]
> > @thomasplevy, While removing the deprecated [`LLMS_Post_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.post.handler.php#L145), I noticed that it is being used by [`LLMS_AJAX_Handler::create_lesson()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/class.llms.ajax.handler.php#L1146), which isn't being used anywhere and would break if it was because `LLMS_Section::count_children_lessons()` was removed in LifterLMS 4.0.0. Should I remove `LLMS_AJAX_Handler::create_lesson()`?
> 
> This should be handled like the other item above you noticed in this situation. I don't want to _remove something_ that will break something that isn't deprecated. So deprecate the other thing and we can remove in 5.x before release (or remove some other time)

`LLMS_AJAX_Handler::create_lesson()` is already broken. The call stack uses `LLMS_Section::count_children_lessons()`, which was removed in LifterLMS 4.0.0.

**Comment by thomasplevy** [comment]
Regardless... like I said above seems like the best avenue forward in my opinion: https://github.com/gocodebox/lifterlms/issues/1886#issuecomment-999867641

If you disagree with me propose a better solution (or just do it and don't ask my opinion :-p)

**Comment by pondermatic** [comment]
> > @thomasplevy, While removing the deprecated[ `LLMS_Section::get_order()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.section.php#L273) method, I noticed that the similar [`LLMS_Lesson::get_order()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.lesson.php#L270) was not deprecated. Want me to make it deprecated?
> 
> OKay!

@thomasplevy, in addition to `LLMS_Lesson::get_order()`, I'm also going to deprecate [`LLMS_Lesson::set_parent_course()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.lesson.php#L669) because it uses the same logic as the deprecated [`LLMS_Section::set_parent_course()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.section.php#L310).

[`LLMS_Lesson::get_parent_course()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.lesson.php#L282) uses a little bit different logic than the deprecated [`LLMS_Section::get_parent_course()`](https://github.com/gocodebox/lifterlms/blob/5.6.0/includes/models/model.llms.section.php#L297). It returns `absint()` on the post meta value instead of the the output of `get_post_meta()`, which if my memory is correct, always returns a string and never an integer. Should I go ahead and deprecate `LLMS_Lesson::get_parent_course()` as well? Maybe we wrap the replacement suggestion with `absint()`?

**Comment by thomasplevy** [comment]
Yes... except I do think that `LLMS_Lesson::get_parent_course()` is used quite a bit internally... possibly explaining why it wasn't deprecated. I'm okay with making the updates and deprecating anyway but please make sure there's not too many add-ons using it.

As war as the use of `absint()`, the replacement would be `get( 'parent_course' )` which is already run through `absint()` in the post model abstract somewhere. The section method should note in the changelog with the deprecation that the return type will change from `string` to `int`.

**Comment by pondermatic** [comment]
`LLMS_Lesson::get_parent_course()` is only used in LifterLMS core and LifterLMS REST. I will submitted a PR for each.

**Comment by pondermatic** [comment]
@gocodebox/engineering,
Now that we warn developers about the deprecated [`lifterlms_created_person`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/forms/class-llms-form-handler.php#L457) action hook, many unit tests, including [`LLMS_Test_Controller_Registration::test_register()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/tests/phpunit/unit-tests/controllers/class-llms-test-controller-registration.php#L27), fail when calling [`do_action( 'init' )`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/tests/phpunit/unit-tests/controllers/class-llms-test-controller-registration.php#L118) because [`LLMS_Engagements::get_trigger_hooks()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L236) returns `lifterlms_created_person` and causes [`LLMS_Engagements::add_actions()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L77) to add the [`LLMS_Engagements::maybe_trigger_engagement()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L458) callback to the `lifterlms_created_person` action hook.

`LLMS_Engagements::get_trigger_hooks()` is used twice.
1. [`LLMS_Engagements::add_actions()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L77)
    I'm assuming that we don't want LifterLMS to add a callback to a deprecated action hook. 
2. [`LLMS_Engagements::parse_hook()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L364)
    I don't understand what this method is doing.

Should we:
1. remove the `lifterlms_created_person` hook from [`LLMS_Engagements::get_trigger_hooks()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L236) 
2. have [`LLMS_Engagements::add_actions()`](https://github.com/gocodebox/lifterlms/blob/dev-600-remove-deprecated-code/includes/class.llms.engagements.php#L77) skip the deprecated `lifterlms_created_person` hook
3. add the `@expectedDeprecated lifterlms_created_person` tag to all of the failing unit tests


UPDATE 2022-01-14 9:00 am -0600 UTC
I am going with option 3.

**Comment by thomasplevy** [comment]
@pondermatic 

I didn't realize we were still using this hook internally. IT should be removed from [LLMS_Engagements::get_trigger_hooks()](https://github.com/gocodebox/lifterlms/blob/f9c3d762b7cc7be2bcc81b939ef78e1ee475a1f0/includes/class.llms.engagements.php#L236) and conditionally re-added only if the hook has actions associated with it (that can be checked with https://developer.wordpress.org/reference/functions/has_action/)

The new hook should be added to this list too.

Additionally, the new hookwith the new one in the list of hooks that might trigger the user registration engagement: https://github.com/gocodebox/lifterlms/blob/f9c3d762b7cc7be2bcc81b939ef78e1ee475a1f0/includes/class.llms.engagements.php#L413-L414. The old hook should be left here (for now) and can be removed when the hook is officially removed.

**Comment by pondermatic** [comment]
@thomasplevy, just making sure I understand.

[`LLMS_Engagements::get_trigger_hooks()`](https://github.com/gocodebox/lifterlms/blob/f9c3d762b7cc7be2bcc81b939ef78e1ee475a1f0/includes/class.llms.engagements.php#L221)
1. should return `lifterlms_user_registered`, which replaced `lifterlms_created_person`
2. should only return `lifterlms_created_person` if it has actions associated with it

[`LLMS_Engagements::parse_hook_find_trigger_type()`](https://github.com/gocodebox/lifterlms/blob/f9c3d762b7cc7be2bcc81b939ef78e1ee475a1f0/includes/class.llms.engagements.php#L408)
1. leave `lifterlms_created_person` until it is removed from [`LLMS_Form_Handler::submit_fields()`](https://github.com/gocodebox/lifterlms/blob/f9c3d762b7cc7be2bcc81b939ef78e1ee475a1f0/includes/forms/class-llms-form-handler.php#L352)
2. add `lifterlms_user_registered`

Is this correct?

**Comment by thomasplevy** [comment]
Yes!
