### ISSUE TITLE
Dev-600: Certificate(s) title(s)

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1888]
Can we clarify the role of the titles in the certificate template and awarded certificate?
Certificate template:
![Schermata 2021-12-16 alle 19 07 31](https://user-images.githubusercontent.com/7689242/146425480-5052d210-488b-4f58-af55-18ffd712f74a.png)
What's the role of the Title under Settings?

Awarded certificate:
![Schermata 2021-12-16 alle 19 05 04](https://user-images.githubusercontent.com/7689242/146425301-a3fd7ca0-94ce-4662-a2d4-ca794dcda86c.png)
Shouldn't "Add Title" be hidden there? As the real title would be the Certificate Title?

**Comment by thomasplevy** [comment]
### Historically -- v 5.x and earlier:

The WP_Post `post_title` on the certificate (template) was used as an admin-only title... 
The meta value  `_llms_certificate_title` stored the actual title of the certificate that users/students would see on the frontend.

When creating an earned certificate (`llms_my_certificate`) both values were copied over.

I don't know what the reason for this differentiation was. The original engagements code was written by Mark and the reason for why we had two titles is unknown to me.

At some point I modified the code of the earned certificate to use the `post_title` in favor of the meta value. Since the admin title was never displayed *anywhere* it seemed superfluous to have the title and meta.

At some point it was also brought to my attention that many people leave the postmeta value *blank* because the automatic display of the title didn't work well on their theme or whatever. This actually creates a UX issue for students where when they earn a cert or view the certs on their dashboard there's no title displayed. So the title is kind of necessary at the very least for this reason and *should not* be left blank.

### 6.x and moving forward

I adjusted the admin UI of the template post type to show "for admin use only"

I've decided that migrating away from using the admin title could cause issues or confusion for users who might actually use the admin title as an admin-only internal title. If we were to migrate the meta value into the post title field we could then erase information that they deemed valuable

So keeping the meta value is somewhat necessary for this reason.

The placeholder heading block with the "Certificate Title" placeholder text was added because I was actually thinking of creating a whole default certificate layout for certs in the block editor. I was also thinking that we could *potentially* create a "template library" for certs to have a few different default options that users could easily select. I never finished or fully realized this. Perhaps finishing a default template layout or deleting the existing one (and having it start blank) would reduce confusion?

### So...

Having explained this... should we adjust anything? Any ideas?

Maybe at the very least the meta value needs some helper text to explain some of this?
