### ISSUE TITLE
Taking over the backend of WP by activating the plugin

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#193]
Hey

I apologize for the lateness of my beta testing, but here goes.

I have installed and just activated and notice Lifter takes over the full WP backend experience similar to what WooCommerce does. I really do not like any plugin etc to take over my screen. It would be better to create a notification giving a few words about neeeding to setup LifterLMS to work. Then clicking the notification and having it jump to a backend screen in the Lifter Settings area. There one could go through the steps of setting up LifterLMS.

I will create issues for each thing as I see it.

**Comment by thomasplevy** [comment]
@paaljoachim thanks for the feedback, I can't guarantee I'm going to implement based on feedback from one user but I will leave this open for feedback from others for the meantime

the real issue for us is that the majority of our users currently ignore our 2.x first run message and then open support tickets within a few days because they haven't taken the necessary install steps to configure LLMS...

it's a tough call and in general, as a user, I don't like the take over either but taking a nod from a successful plugin like WC is a good start in helping us onboard new users

**Comment by paaljoachim** [comment]
Well you got some good reasons there. Just stick with it and keep it as it is..:)
