### ISSUE TITLE
[6.0] When awarding certificate - option to pull in certificate template

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#1965]
**Is your feature request related to a problem? Please describe.**
When awarding a certificate, we want to pull in a template to associate that individual awarded certificate with, so in future updates of the certificate template, it can sync and make it faster to recreate certificate from a course program for example.

https://www.loom.com/share/e6b4c3d2cb3d4ebebac72b1d3ff5f098

**Describe the solution you'd like**
An option on the award certificate edit page to create from certificate template

**Describe alternatives you've considered**
Global blocks (but that only solves the problem of initially creating it rather than updating it from the template down the line)

**Comment by thomasplevy** [comment]
I like this idea a lot... A few thoughts I'm having about it... You're opinion appreciated @eri-trabiccolo 

A) Should we simply add a searchable select field to lookup templates? EG: create a new awarded certificate and then select the template from the sidebar?

B) Alternatively we could "hijack" the interface when loading a new certificate and pop a one-time use modal that says "Would you like to create from a template or start from scratch? The start from scratch closes the modal, the template option provides a searchable select. 

In either case after selecting we'll either need to use the block editor apis to load all the possible metadata / post content / title / etc... into the current instance or we can (probably easier) reload the page and perform the syncing serverside (we've already built all of that).


I'm leaning towards B, I think... There's some complications with existing logic that the user can't be changed after it's awarded so we maybe will need to adjust the way this all works to allow the template to be selected before the user. Or, with be, we could force the user to be selected first... perhaps? We'd want to make sure it's saved as a draft (not published) so that it's not awarded until the certificate creator is happy with everything. We want them to be able to preview it all before awarding it.


Additionally, I think we could add a metabox from the template editor that allows awarding the certificate directly to a student from the template page. This... actually now that I'm thinking about it, may be the better way to do it and resolves complications with the above paragraph. If the template is "ready" and they click an "award to student" button it can pop a modal with a student selector and possibly an "award now", "schedule" or "create draft" option. Then on click we can programmatically create a new `llms_my_certificate`, load the user and the template id and the correct post status, and then run the (already-existing) sync operation. We won't have to mess with much block editor API and worry about reloading and etc...

We could also potentially add functionality from the student reporting screen as well. Currently there's an "Award Certificate" button that opens the editor for the `llms_my_certificate` post type with the student prepopulated. We could mimc this behavior but allow selecting a template first. The current "Award" button pops a modal that allows a template selection for the current user (instead of a user selection for the current template). This is maybe not essential as a secondary entry point but it's possible.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I'm for B) as well.

> This... actually now that I'm thinking about it, may be the better way to do it and resolves complications with the above paragraph.

I think we need 3 entry point:
1) from the template editor, as you suggested: pop-up with only a student selector...
2) from the student reporting, as you suggested: pop-up with only a template selector or "start from scratch"
3) Add new from the awarded certificates post list table: pop-up with a student selector AND a template selector/start from scratch - student and template/start-from-scratch are required

What do you think? We don't need to care about drafts this way?!

**Comment by thomasplevy** [comment]
Yea I think that makes sense. Why are you saying we don't need to care about drafts? Are you saying that it should *always* automatically award the cert (create it as published)?

I'm thinking that by default it should but it wouldn't be that much additional work to at least add an option to create it as a draft (scheduling it could be omitted, if they want to schedule, create a draft and then schedule it from the editor).

Either way it should reload the page to the editor with it either already-published or saved as a draft.

**Comment by thomasplevy** [comment]
Also: I think we could build this as a single react (button + modal) component that can be loaded into the 3 different areas passing in a "context" parameter which will determine which selectors are to be displayed.

We haven't yet loaded react outside of the block editor but it's actually quite easy to do. I wouldn't call it lightweight as far as a code footprint is concerned but my guess is that the WP core will start to react-ify more and more of the admin panel anyway and building a single react component for use in these 3 places will be easier to maintain that building a react component for the editor and a vanilla js version for the other two places.

**Comment by eri-trabiccolo** [comment]
> Also: I think we could build this as a single react (button + modal) component that can be loaded into the 3 different areas passing in a "context" parameter which will determine which selectors are to be displayed.
> 
> We haven't yet loaded react outside of the block editor but it's actually quite easy to do. I wouldn't call it lightweight as far as a code footprint is concerned but my guess is that the WP core will start to react-ify more and more of the admin panel anyway and building a single react component for use in these 3 places will be easier to maintain that building a react component for the editor and a vanilla js version for the other two places.

Agree!

**Comment by eri-trabiccolo** [comment]
> Yea I think that makes sense. Why are you saying we don't need to care about drafts? Are you saying that it should _always_ automatically award the cert (create it as published)?
> 
> I'm thinking that by default it should but it wouldn't be that much additional work to at least add an option to create it as a draft (scheduling it could be omitted, if they want to schedule, create a draft and then schedule it from the editor).
> 
> Either way it should reload the page to the editor with it either already-published or saved as a draft.

I mostly think:
- does make sense changing the status of a published certificate into a draft?
- should we allow to change template/student when a cert is in draft status?

Also, what happens when we create and awards as draft? Is the engagement related to the awarding fired?
I guess it's not... Well I think we have the same "problem" with the scheduled.
I think we need also a `post_status` transition listener. mmm....

**Comment by thomasplevy** [comment]
It's currently setup so that the *awarding action* (which will fire the notification that the student earned a certificate) only runs the *first time* a certificate is published:

https://github.com/gocodebox/lifterlms/blob/dev-600/includes/controllers/class-llms-controller-awards.php

Specifically see: https://github.com/gocodebox/lifterlms/blob/19a5b1e67a4ad7b0cbff6caf027d890f62f7a95e/includes/controllers/class-llms-controller-awards.php#L140-L153

I'm not entirely sure if this is the final or best approach, but my thinking was:

1) Students should not get a notification every time a certificate is updated.
2) If an admin switches it to draft and then publishes it again later they've technically already earned it... So we don't need to alert them to being awarded the same thing again.

Perhaps it should really be anytime the status changes from any other status to publish. In which case we'd just need to adjust that hook to run on transition post status as you've suggested.



> does make sense changing the status of a published certificate into a draft?

I don't know... I think that we should allow the ability to do so (we do in the current 6.x release) and I think it will be difficult to remove the ability to transition to draft in the block editor. I believe I figured out how to do it with forms but it was hacky.

> should we allow to change template/student when a cert is in draft status?

Currently you cannot change the template at all... I don't know if you *should* be able to... Part of me thinks that we *should not* allow the template to change. Especially if we implement this feature in this thread if you want to change the template you should just award a new certificate and delete the existing one. Right...? But also semantically what's the difference between changing the template and updating the certificate itself.

You cannot -- and I think should not -- be able to change the student once it's been awarded. The permalink will not change and the sharing status would need to be reset and etc... I think that... generally... We should just say "Once it's been awarded (published for the first time) it's locked to that student. I think this is reasonable and makes sense. And with this functionality to create from a template on demand if you really want to "switch" the student you can create a new one for the new student from the template and delete the one you want to switch.

**Comment by thomasplevy** [comment]
If we allow changing the template.... I guess we should... it should treat it as an update, in my opinion... What does the interface for changing a template look like? I guess that would be select + confirm the change and reload (merging the new data serverside)

**Comment by eri-trabiccolo** [comment]
Yeah I think your code, and mine prior to this, didn't think about the fact that that the action should be triggered when a post transitions to `published` the first time. So if I create a certificate in `future` status the action should run when it will be published.

> Currently you cannot change the template at all... I don't know if you should be able to... Part of me thinks that we should not allow the template to change. Especially if we implement this feature in this thread if you want to change the template you should just award a new certificate and delete the existing one. Right...? But also semantically what's the difference between changing the template and updating the certificate itself.

Yeah you're right.

> You cannot -- and I think should not -- be able to change the student once it's been awarded. The permalink will not change and the sharing status would need to be reset and etc... I think that... generally... We should just say "Once it's been awarded (published for the first time) it's locked to that student. I think this is reasonable and makes sense. And with this functionality to create from a template on demand if you really want to "switch" the student you can create a new one for the new student from the template and delete the one you want to switch.

You're right on this too, dammit.

> If we allow changing the template.... I guess we should... it should treat it as an update, in my opinion... What does the interface for changing a template look like? I guess that would be select + confirm the change and reload (merging the new data serverside)

Yeah, confirm the change with a warning on what's going to happen.

**Comment by thomasplevy** [comment]
> Yeah I think your code, and mine prior to this, didn't think about the fact that that the action should be triggered when a post transitions to `published` the first time. So if I create a certificate in `future` status the action should run when it will be published.

The way it's written right now it'll trigger the creation action / award notification when the scheduled post is published. Since this is currently running on `save_post_{$post_type}`. I am pretty sure I looked into this and that when a scheduled post is published it'll run `wp_update_post()` to update the post_status property, triggering this hook and causing the notification to be generated.

**Comment by eri-trabiccolo** [comment]
Ohh yeah, fine so.

**Comment by thomasplevy** [comment]
I've made some progress

https://user-images.githubusercontent.com/1290739/155419488-14158d0c-519b-4471-98b5-b0676e687824.mp4
