### ISSUE TITLE
[6.0] Certificate's inner elements are responsive and probably they should be not

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1972]
### Reproduction Steps

+ Create a certificate template with the default content
+ View it
+ emulate a mobile device

### Expected Behavior

+ I would expect it to be not responsive, e.g. the columns not stacked, or the font-size kept as in desktop viewport

### Actual Behavior

+ The certificate's inner elements are responsive

### Error Messages / Logs

n/a

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
The best would be to have the certificates completely unresponsive.
If we can't achieve this we should at least prevent the columns to stack on mobile (with a simple CSS override).

**Comment by thomasplevy** [comment]
@eri-trabiccolo We talked briefly about some potential solutions here. Want to try some of that out and let me know if any of those (or other) ideas could be a viable solution?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Looks like I'm not able to avoid the "responsiveness" by setting a fixed content as meta viewport. E.g.:
`<meta name="viewport" content="width=500, initial-scale=1">`
just doesn't seem to be honored at all.
And I don't have any idea on how to fix this unfortunately.
I think we can tell the columns block to not stack on mobiles in certificates, but I wouldn't know how to avoid other CSS for small viewports to be applied, e.g. theme's font-sizing rules, ecc.

**Comment by thomasplevy** [comment]
@eri-trabiccolo dare I say this is the stupidest thing I've ever done:

```js
<script>
(function(){

	let remaining = true,
		exec = 0;

	while ( remaining ) {
		++exec;
		console.log( `Executions: ${ exec }` );
		remaining = 0 !== removeMQs();
	}

	function removeMQs() {

		let deleted = 0;

		const stylesheets = document.styleSheets;
		for ( let i = 0; i < stylesheets.length; i++ ) {

			const stylesheet = stylesheets[i];
			[].forEach.call( stylesheet.cssRules || [], ( { cssText }, j ) => {
				if ( cssText.includes( '@media (min-width:' ) || cssText.includes( '@media (max-width:' ) ) {
					stylesheet.deleteRule( j );
					++deleted;
				}
			} );

		}

		console.log( `Deleted MQs: ${ deleted }` );

		return deleted;

	}


} )();
</script>
```

https://user-images.githubusercontent.com/1290739/154340877-f251fa58-f133-4c65-ba87-8bf792630506.mp4

**Comment by thomasplevy** [comment]
What is that monstrosity? I'll tell you... On page load it finds every max and/or min-width MQ and REMOVES IT so that nothing on the page will be responsive... ever...

This *does actually work* however it fails spectacularly if the theme is mobile-first. As this will leave only mobile styles. I can't imagine we could actually figure out a way to determine if a theme is truly mobile first programmatically.

We could choose a max-width and only remove media queries below that threshold... Ideally we'd do that based on the width of the certificate but we have to also take pixel density into account then

Another note: I've tested our code on various devices through browser stack and on mobile devices, since we have no viewport declaration, it loads the site unresponsive as we'd like.

The problem we have really arises actually on smaller desktop browser, either when resized in a smaller window or when manually resizing the browser on purpose . I have no idea how to reliably combat this.

**Comment by thomasplevy** [comment]
I can't figure out a descent way to filter the default value of `isStackedOnMobile` to `false` for the columns block. I'm going in circles and for now I'm moving on... If you want to take a stab at it go ahead...

I'm currently leaning towards creating a forked version of the column block that has the stacking options removed. And then de-registering the core columns block for certificate post types... I don't have the energy to do this right now.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I tried as well, I keep on getting validation error b/c of the mismatch between the `save` result and the `edit` result.
Then the block actually works as expected, in any case I see there's no easy way to hide the stacking option in the inspector.

So I guess the forked version is the best solution here.

**Comment by thomasplevy** [comment]
I can't make this work by forking the block either. The columns block is very complicated and in order to get this working we're going to have to copy code from 5 or 6 different files in the WP core... this feels like a maintenance nightmare to me.

I'm currently back to messing with every single possible combination of filters I can find to change the default value without popping the validation error. This is feeling like an insurmountable task currently...
