### ISSUE TITLE
LifterLMS Forms + Essential Addons for Elementor

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2052]
### Reproduction Steps

+ HS-188601
+ LifterLMS + Elementor + Essential Addons for Elementor
+ Head into LifterLMS ->Forms
+ Hover over one of the forms and you'll see "EA Duplicator" click the duplicator

### Expected Behavior

+ The forms can't be cloned 
+ Though, they can't be cloned normally, so if you're using a third party plugin to get around this that's kind of on the user?

### Actual Behavior

+ The form is cloned but it is not not deletable because the form is being read as a core registration/checkout form or a default one with Custom Fields enabled. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 5.10.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-One
Version: 1.5
Themeuri: https://wordpress.org/themes/twentytwentyone/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Elementor: 3.5.6
Essential Addons for Elementor: 5.0.10
LifterLMS: 6.0.0
LifterLMS Advanced Videos: 1.0.0-beta.17
LifterLMS PDFs: 2.0.1
User Switching: 1.5.8
WP Mail Logging: 1.10.4


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS PDFs: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
The thing is that our forms are not meant to be cloned/duplicated (not in the core plugin at least, we can debate on whether implement our cloning system in the add-on). Reasonably we cannot 100% prevent 3rd parties cloning the form posts, but we could mitigate this, by deciding that our core forms can only have the actions.
- `view`
- `edit`
Basically we define an `allowlist` and filter out the disallowed actions, using this filter but with a very low priority (e.g. PHP_INT_MAX - 1 ):
https://github.com/gocodebox/lifterlms/blob/6.0.0/includes/admin/post-types/post-tables/class-llms-admin-post-table-forms.php#L31


I don't think we need to create a specific tool now to delete the form the customer cloned. Also because I don't think we really have a way to determine which one of the two is the cloned one. For such a situation to be honest, the "cloned" form must be manually deleted by the customer, e.g. `<?php wp_delete_post( $clone_form_id, true ); ?>`.


@gocodebox/engineering what do you think about the strategy?

**Comment by thomasplevy** [comment]
@eri-trabiccolo I wonder if we should change our strategy of determining which forms are core and which ones are added via other means (be it duplication via a 3rd party plugin or via creation via custom fields).

Instead of using `_llms_form_is_core` metdata, we could create a new option that stores the `WP_Post` ids of the core forms (as an array).

I haven't read through all of the code to determine if this would be a viable strategy but it might simplify fixing conflicts like this one.

**Comment by eri-trabiccolo** [comment]
> @eri-trabiccolo I wonder if we should change our strategy of determining which forms are core and which ones are added via other means (be it duplication via a 3rd party plugin or via creation via custom fields).
> 
> Instead of using `_llms_form_is_core` metdata, we could create a new option that stores the `WP_Post` ids of the core forms (as an array).

> I haven't read through all of the code to determine if this would be a viable strategy but it might simplify fixing conflicts like this one.

I actually thought about this as well, and could make sense, yeah, but I also thought that for this very problem it still won't prevent the duplication, it will just allow for trashing after duplication. Actually at the moment we filter out non-core forms, so we would need to change this behavior too in order to allow the deletion :D

I don't know man, I think keeping track is pretty good, but I don't think we need it, not at the moment.

**Comment by thomasplevy** [comment]
@eri-trabiccolo we have several reports of people being unable to delete "core" forms that were created (somehow) in error though: https://github.com/gocodebox/lifterlms/issues/1685

I haven't been able to identify the cause of these duplications in #1685 but the end result is the same: forms exist that cannot be cleaned up.

I don't think telling people they need to manually delete them via code is the correct answer in any event...

But I agree that rewriting how we determine could be more work than it's worth...

What if we add a fallback query that will check if the core form is the only core form on the site and then, if it is, allow deletion for all forms except the form with the lowest number id?

**Comment by eri-trabiccolo** [comment]
> What if we add a fallback query that will check if the core form is the only core form on the site and then, if it is, allow deletion for all forms except the form with the lowest number id?

I thought the same, yeah should work. Yeah let's do it.
