### ISSUE TITLE
Syncing Changes Earned Date 

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2069]
### Reproduction Steps

+ HS-189146
+ Create a Template->Assign user a certificate from that template
+ Go into template and sync assigned certificates

### Expected Behavior

+ changes to the certificate should take affect but the earned date should remain for earned certificates.

### Actual Behavior

+ While the earned date on reporting and under awarded certificates remains the original earned date, the certificate itself displays the last sync date.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Homepage (#1398) [https://natalie-test-site.myliftersite.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.7.9
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 6.0.0
Loco Translate: 2.6.1
User Switching: 1.5.8
WP Mail Logging: 1.10.4
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 can you confirm this is using the mergecode `{current_date}` to display the date on the certificate?

**Comment by thomasplevy** [comment]
If that's the case then I think what we have here is a need to add a new merge code...

Semantically `{current_date}` would have historically always functioned to output the awarded date. There was no way to update resync or update earned certs so that date would always be the earned date. It would never change.

Now that we can sync this merge code makes less sense but changing it to merge in the original earned certificate date in favor of the current date would be confusing because, well, it literally says "current date" in the text of the code. If a user was expecting it to output the current date (in favor of the earned date) but it output the earned date, they'd be confused and report that as a bug. And they'd be both correct and incorrect.

So I think the solution here should be to add a new merge code `{earned_date}` which will always output the earned date. When awarding a certificate for the first time that'll be the same as `{current_date}`.

Our default template should likely use this new merge code and the `{current_date}` merge code becomes less useful and less sensible but should still exist for backwards compat reasons if no other reasons.

**Comment by nrherron92** [comment]
@thomasplevy yes the template uses {current_date} though the awarded certificate doesn't have a merge code when you edit it. It is just a printed date.

**Comment by thomasplevy** [comment]
@nrherron92 alright we'll have to add a new merge code to handle this. When syncing the `{current_date}` is being remerged. Which as I've noted above is the semantically correct (although for existing users probably not expected) behavior.

We can't just change current date but we do need to implement a better solution.

We'll get to work on this right away.

In the meantime there's a few things to note:

The actual earned date is *not* being changed (as evident in reporting). So the issue here is in in the use of the merge code. This means that when a new replacement merge code is used that can be added to the template and the templates can be resynced and the initial earned date will be present.

There's nothing we can do immediately to rectify the issue that this has created. We'll need to implement a new merge code that can be used in place of the old one as needed.

I know this user is very unhappy about this and my justification (that semantically it's doing what it says it's doing) doesn't help, but this is the reality. There's an oversight in development that we should have implemented this new merge code with the release of 6.0.

I'm not sure whether or not we should have replaced `{current_date}` with a new `{earned_date}` merge code on existing certificates. The semantic different between current and earned really does matter once you can sync things.

**Comment by thomasplevy** [comment]
@gocodebox/engineering I'm not going to be able to get to work on this today or maybe even tomorrow so if anyone has some availability to pick this up it should be pretty quick to implement a new merge code.
