### ISSUE TITLE
Manual Payment Not Capturing Name

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2166]
### Reproduction Steps

+ HS-193690
+ I can't reproduce locally or on staging
+ Purchase a course using the manual payment option
+ Fill out user information and enroll
+ Examples/Links on ticket

### Expected Behavior

+ user's first name/last name and addresses should be captured in the order

### Actual Behavior

+ Only the email appears to be captured

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/login/
Version: 5.9.3
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: en_GB
Multisite: No
Page For Posts: Not Set
Page On Front: Welcome to the National Network of Mental Health Leads (#8) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.6.0
Db Version: 6.6.0
Course Catalog: Course Catalogue (#31) [[removed]/courses/]
Membership Catalog: Membership Catalogue (#32) [[removed]/memberships/]
Student Dashboard: Dashboard (#34) [[removed]/dashboard/]
Checkout Page: Purchase (#33) [[removed]/purchase/]
Course Catalog Per Page: -1
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: medium
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: GB
Currency: GBP
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: yes
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

PayPal: Disabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 0
Manual: Enabled
Manual Logging: no
Manual Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 2


Server
-------------------------------------------

Mysql Version: 5.6.51
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 32 MB
Php Memory Limit: 256M
Php Post Max Size: 32M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.18
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.8.1
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

BuddyBoss Platform: 2.0.1.1
E2Pdf: 1.16.48
Formidable Directory: 1.0.01
Formidable Forms: 5.3
Formidable Forms Pro: 5.2.07
Formidable Registration: 2.07
Formidable Surveys: 1.0.05
Formidable Visual Views: 5.1.05
Hide Admin Bar From Front End: 3.2.0
Insert Headers and Footers: 1.6.2
LifterLMS: 6.6.0
LifterLMS Advanced Quizzes: 2.0.1
LifterLMS Advanced Videos: 1.0.0-beta.18
LifterLMS Custom Fields: 2.0.2
LifterLMS Formidable Forms: 1.0.5
LifterLMS Groups: 1.0.0-beta.20
LifterLMS Helper: 3.4.2
LifterLMS PayPal Gateway: 1.4.0
LifterLMS Private Areas: 1.1.5
LifterLMS Social Learning: 1.5.0
LifterLMS Stripe Payment Gateway: 5.4.0
Loco Translate: 2.6.2
PublishPress Revisions Pro: 3.0.16
Simple Custom CSS: 4.0.5
Theme My Login: 7.1.4
Theme My Login Redirection: 1.1
User Menus: 1.2.9
User Switching: 1.5.8
WP Mail SMTP Pro: 3.4.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes
LifterLMS Groups: Yes
LifterLMS Formidable Forms: Yes
LifterLMS Private Areas: Yes
LifterLMS Social Learning: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@nrherron92 
where's the staging website?

I don't think the issue is related to the manual payment at all.
For what I can see this happens on some forms (customer has several forms) and not only for the First/Last Name.
Basically what happened is that, e.g., the First/Last Name form fields which must be tied to the WordPress's user First and Last name, have become (for some reason we need to investigate) like custom fields. This is the screenshot of one of the "incriminated" checkout forms. See the First Name field's `name` attribute's value, it should be `first_name` (which maps to the WordPress's user first name), while it's `text_8687_3`.
![Schermata 2022-05-26 alle 11 22 42](https://user-images.githubusercontent.com/7689242/170459591-ab4d3d40-7e2e-4a13-8658-d71c71f15786.png)

We need to find the reason for this but, for the customer in question, now the data collected through those forms, are saved in different locations than the expected, and since the user information of an order are not dynamic, but added to the order when the order is created, even manually filling the first/last name manually won't reflect in the order information...

The malformed forms need to be reworked, basically the customer would have to remove the wrong fields and add them back.
Note that prior to remove the "wrong" fields would be better that data filled by their users is moved into the actual fields, as these "wrong" fields are visible in the users profile, but when they'll be removed from all the forms they won't appear there anymore.

**Comment by thomasplevy** [comment]
@eri-trabiccolo just looking through open todos and it looks like https://github.com/gocodebox/lifterlms-blocks/issues/169 is what needs fixing (actually you've already fixed and we're holding).

Is this issue safe to close @eri-trabiccolo and @nrherron92 ?

**Comment by nrherron92** [comment]
Yes! If @eri-trabiccolo is good to go this can be closed!

**Comment by eri-trabiccolo** [comment]
@thomasplevy yeah I think it's fine.
