### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by younes-dro** [gocodebox/lifterlms#2247]
Hi.
even i deactivated the plugin i still get this Notice : 
`[26-Aug-2022 22:06:07 UTC] PHP Notice:  Function map_meta_cap was called <strong>incorrectly</strong>. The post type llms_order is not registered, so it may not be reliable to check the capability "read_post" against a post of that type. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.4.0.) in C:\wamp64\www\expresstechsoftware\wp-includes\functions.php on line 5831`

**Comment by thomasplevy** [comment]
@younes-dro 

This likely has to do with a user role. Roles aren't removed when the plugin is deactivated unless you explicit tell LifterLMS to remove data from your site during deactivation: 

https://github.com/gocodebox/lifterlms/blob/0836531192028c820f6d8b25469950686ff095c9/uninstall.php#L24-L28

It seems weird to me that a user role would be checking anything against a LifterLMS post type when the plugin is deactivated though. It's hard to debug this further or recreate with this minimal set of information.

Do you have any additional information you could provide for us about this other than what you have above? Any steps you took before this action?

If you're simply trying to completely remove LifterLMS and not use it anymore you can use the above-refereneced constant to remove all data during plugin installation. We _very intentionally_ don't do this by default since deactivating (and sometimes even deleting and reinstalling) plugins is very common for users when trying to debug conflicts.

**Comment by eri-trabiccolo** [comment]
This actually happens on the WordPress dashboard page: wp-admin/index.php when LifterLMS is disabled, because of the Activity widget showing the recent comments (order notes are implemented as order's post type's comments).
Basically when checking if:
- the current user can read the comment's (order note) parent post (`llms_order` type)
- or the current user can edit the comment.

defining `LLMS_REMOVE_ALL_DATA` as `true` prior to disabling the plugin does solve the issue, because that ensures the removal of the order posts (although we should remove the `llms_order_note` comment type as well.)

I don't think there's anything we can do on this more than we already do (which is the same thing WooCommerce does), as long as our orders continue to be post types and the order notes post comments.

@younes-dro 
I'm closing this, but please feel free to re-open this issue if you need further clarifications. <3

**Comment by eri-trabiccolo** [comment]
related WordPress issues on trac:
https://core.trac.wordpress.org/ticket/49437
https://core.trac.wordpress.org/ticket/36208
