### ISSUE TITLE
PHP Notice: Trying to get property 'id' of non-object 

### ISSUE THREAD

**Issue by younes-dro** [gocodebox/lifterlms#2287]
Hi ,
I'm trying to process the setp of a new plugin
and I get this PHP notice in some page in admin area:

`Notice: Trying to get property 'id' of non-object in C:\wamp64\www\expresstechsoftware\wp-content\plugins\lifterlms\includes\admin\class.llms.admin.assets.php on line 406`

`Notice: Trying to get property 'base' of non-object in C:\wamp64\www\expresstechsoftware\wp-content\plugins\lifterlms\includes\admin\class.llms.admin.assets.php on line 410`

The url where this notice is displayed: `http://127.0.0.2:8000/wp-admin/index.php?page=PLUGIN-setup`.

`$screen = get_current_screen();` return NULL.

**Comment by eri-trabiccolo** [comment]
Hi @younes-dro 
thanks for reporting this.
Can you please give us more information?
E.g. what's this plugin you're trying to setup?

Also: aside from this notice are you able to setup the plugin correctly?

Thanks!

**Comment by younes-dro** [comment]
@eri-trabiccolo 

The plugin is LearnPress. I was testing some plugins we develop with LifterLMS and LearnPress.

1 - the plugin is learnpress and url  : http://127.0.0.2:8000/wp-admin/index.php?page=lp-setup.

2 - Yes i  setup the plugin correctly.

**Comment by eri-trabiccolo** [comment]
Thanks @younes-dro!
I wonder why in that LP's setup wizard's page the WordPress current screen is not defined...
This is a wild world :D

It could be fixed on our side by checking the `$screen` is not null prior to referring to its properties. E.g. here:
https://github.com/gocodebox/lifterlms/blob/7.0.0/includes/admin/class.llms.admin.assets.php#L401
```php
if ( ! $screen ) {
	return;
} 
```

But the truth is that when WordPress fires that hook, the current screen is set!
To me this is a LearnPress issue since they fire the WordPress hook [admin_print_scripts](https://developer.wordpress.org/reference/hooks/admin_print_scripts/ ) without setting the `$current_screen`.

See where WP fires the hook in the `admin-header.php`:
https://github.com/WordPress/WordPress/blob/6.0.3/wp-admin/admin-header.php#L146
way after the current screen is set:
https://github.com/WordPress/WordPress/blob/6.0.3/wp-admin/admin-header.php#L32

While LearnPress fires the same hook (which, again, it's a WordPress hook, not a LearnPress or a LifterLMS hook, so if you fire it you have to make sure you created a consistent _environment_) from here:
https://plugins.trac.wordpress.org/browser/learnpress/tags/4.1.7.2/inc/admin/class-lp-setup-wizard.php#L149(this is where they call their wizard's header template)
https://plugins.trac.wordpress.org/browser/learnpress/tags/4.1.7.2/inc/admin/views/setup/header.php#L20

So I don't think this is something we need to address.

@gocodebox/engineering opinions?

**Comment by thomasplevy** [comment]
I don't think there's any reason for us to address this.
