### ISSUE TITLE
Default sidebar widgets showing in footer on course page

### ISSUE THREAD

**Issue by stepherrific** [gocodebox/lifterlms#231]
Widgets from the default sidebar (which I'm not using) are being displayed in the footer on some of the automatically generated pages. 

Here's a link to the Course page: http://stei.brewingsweettea.com/courses/

And this is what the footer is supposed to look like (both the light and dark gray sections): http://stei.brewingsweettea.com/

Thanks for any help!

This site is under active development, so here's a screenshot as well in case the link isn't displaying properly.
![capturfiles-201610286_1210](https://cloud.githubusercontent.com/assets/7013505/19318019/f749af86-9074-11e6-8d50-bfb2a1a6646b.jpg)

**Comment by stepherrific** [comment]
This is happening on the Membership page, too. FYI.
http://stei.brewingsweettea.com/memberships/

**Comment by thomasplevy** [comment]
@stepherrific sorry theres issues here -- can you check out our bug report guide and get me a copy of your system report before I proceed: https://github.com/gocodebox/lifterlms#reporting-a-bug

At a minimum I need to know your theme and version, thanks

**Comment by stepherrific** [comment]
Thanks for the quick response, Thomas! 

I'm running a child theme with Divi 3.0.14 and WP 4.6.1.

Here's my report:

Wordpress
-------------------------------------------

Home Url: http://stei.brewingsweettea.com
Site Url: http://stei.brewingsweettea.com
Version: 4.6.1
Debug Mode: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#1214)
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.0.0
Course Catalog: Courses (#1221)
Course Catalog Per Page: 10
Course Catalog Sorting: menu_order
Membership Catalog: Memberships (#1219)
Membership Catalog Per Page: 10
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Student Dashboard: My Courses (#1225)
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: hidden
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: required
Registration Address: required
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: hidden
Account Email Confirmation: no
Checkout Page: Purchase (#1223)
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: webmaster@enjoysweettea.com
Email From Name: STEI Website
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.6.28
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 128 MB
Php Memory Limit: 768M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 5.6.26
Software: Apache
Wp Memory Limit: 128M


Theme
-------------------------------------------

Name: Divi Child Theme by Sweet Tea for STEI
Version: 
Themeuri: 
Authoruri: 
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Divi Booster: 2.3.3
Elegant Themes Updater: 1.0
LifterLMS: 3.0.0
ManageWP - Worker: 4.2.9
TablePress: 1.7


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No

**Comment by thomasplevy** [comment]
@stepherrific i'm not seeing this issue locally

I've added widgets to the "Default Sidebar" and they display in the sidebar, widgets in the "Footer Widets" are displaying in the footer

As far as course and lesson sidebars are concerned, if you want those to work with Divi today you can use this guide and add a filter: https://lifterlms.com/docs/lifterlms-sidebar-support/#code-snippet

For Divi you want to use "sidebar-1" as the sidebar ID

The patch to add theme support will be released in 3.0.1

**Comment by pakfones** [comment]
Hi, I have exact same problem course and lesson sidebar working 

I ma using Impreza 4.7 and i have added code snippet written about Impreza Theme on [this page](https://lifterlms.com/docs/impreza-theme-course-and-lesson-sidebar-compatibility/) in themes functions.php. I also tried super sidebar but i still not solved, i have all Pages, Archives and Categories links under course in footer. You can all system information below. Please let me know where i have done any mistake? or anything need to be added additionally.

The pages that not working.
https://pakfones.com/courses/
https://pakfones.com/memberships/

Thanks In Advance!

`Wordpress
-------------------------------------------

Home Url: https://pakfones.com
Site Url: https://pakfones.com
Version: 4.8.3
Debug Mode: No
Locale: en_US
Multisite: No
Page For Posts: BLOG (#4938)
Page On Front: HOME (#8)
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.14.7
Db Version: 3.14.7
Course Catalog: Course Catalog (#12319)
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog: Membership Catalog (#11634)
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Student Dashboard: My Courses (#11581)
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Terms & Conditions (#2261)
Checkout Names: required
Checkout Address: required
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: hidden
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: required
Account Email Confirmation: yes
Checkout Page: Purchase (#11580)
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: PK
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: support@pakfones.com
Email From Name: PAKFONES.COM
Email Footer Text: 
Email Header Image: 11722
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.6.23
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 2000
Php Max Upload Size: 16 MB
Php Memory Limit: 512M
Php Post Max Size: 16M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 0
Php Version: 7.1.10
Software: Apache
Wp Memory Limit: 40M


Theme
-------------------------------------------

Name: Impreza
Version: 4.7
Themeuri: http://impreza.us-themes.com/
Authoruri: http://us-themes.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

A2 Fixed W3 Total Cache: 0.9.4.6.4.2
A2 Optimized WP: 2.0.9.4
Advanced Ads: 1.8.12
Advanced Ads – Visual Composer: 1.0.3
All-in-One WP Migration: 6.59
All In One WP Security: 4.2.9
Cloudflare: 3.3.1
EWWW Image Optimizer: 4.0.1
Force Regenerate Thumbnails: 2.0.6
Jetpack by WordPress.com: 5.4
LifterLMS: 3.14.7
LifterLMS Labs: 1.4.0
Loginizer: 1.3.8
MailChimp for WordPress: 4.1.11
Slider Revolution: 5.4.5.1
Slimstat Analytics: 4.7.2.2
SSL Insecure Content Fixer: 2.4.0
Tawk.to Live Chat: 0.3.3
Ultimate Addons for Visual Composer: 3.16.13
UpSolution Header Builder: 2.0.2
WooCommerce: 3.2.3
WooCommerce Checkout Manager: 4.1.6
Wordfence Security: 6.3.21
WordPress Importer: 0.6.3
WP-PostViews: 1.75
WP-SpamShield: 1.9.21
WPBakery Visual Composer: 5.2
Yoast SEO: 5.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------


Wordpress
-------------------------------------------

Home Url: https://pakfones.com
Site Url: https://pakfones.com
Version: 4.8.3
Debug Mode: No
Locale: en_US
Multisite: No
Page For Posts: BLOG (#4938)
Page On Front: HOME (#8)
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.14.7
Db Version: 3.14.7
Course Catalog: Course Catalog (#12319)
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog: Membership Catalog (#11634)
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Student Dashboard: My Courses (#11581)
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Terms & Conditions (#2261)
Checkout Names: required
Checkout Address: required
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: hidden
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: required
Account Email Confirmation: yes
Checkout Page: Purchase (#11580)
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: PK
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: support@pakfones.com
Email From Name: PAKFONES.COM
Email Footer Text: 
Email Header Image: 11722
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.6.23
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 2000
Php Max Upload Size: 16 MB
Php Memory Limit: 512M
Php Post Max Size: 16M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 0
Php Version: 7.1.10
Software: Apache
Wp Memory Limit: 40M


Theme
-------------------------------------------

Name: Impreza
Version: 4.7
Themeuri: http://impreza.us-themes.com/
Authoruri: http://us-themes.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

A2 Fixed W3 Total Cache: 0.9.4.6.4.2
A2 Optimized WP: 2.0.9.4
Advanced Ads: 1.8.12
Advanced Ads – Visual Composer: 1.0.3
All-in-One WP Migration: 6.59
All In One WP Security: 4.2.9
Cloudflare: 3.3.1
EWWW Image Optimizer: 4.0.1
Force Regenerate Thumbnails: 2.0.6
Jetpack by WordPress.com: 5.4
LifterLMS: 3.14.7
LifterLMS Labs: 1.4.0
Loginizer: 1.3.8
MailChimp for WordPress: 4.1.11
Slider Revolution: 5.4.5.1
Slimstat Analytics: 4.7.2.2
SSL Insecure Content Fixer: 2.4.0
Tawk.to Live Chat: 0.3.3
Ultimate Addons for Visual Composer: 3.16.13
UpSolution Header Builder: 2.0.2
WooCommerce: 3.2.3
WooCommerce Checkout Manager: 4.1.6
Wordfence Security: 6.3.21
WordPress Importer: 0.6.3
WP-PostViews: 1.75
WP-SpamShield: 1.9.21
WPBakery Visual Composer: 5.2
Yoast SEO: 5.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------


`

**Comment by thomasplevy** [comment]
@pakfones [GitHub is *not* a support form](https://github.com/gocodebox/lifterlms#getting-help-and-support-support)

I'd like to help but I cannot: In short: I cannot buy every premium theme to test integration issues like this and help resolve them so I'll need to acquire a copy of your theme.

If you have access to support please submit a new support ticket regarding this issue and provide us with a copy of your theme so I can recreate this locally and advise.

Thanks,

**Comment by pakfones** [comment]
@thomasplevy 

Sorry for that but sent you a copy of Impreza Theme via email. It would be great if you can add integration in next update of LifterLMS Labs plugin or any tutorial for Impreza theme users.

Thanks in advance,

**Comment by thomasplevy** [comment]
@pakfones I don't accept support requests for any reason on my personal email and I do not budge on this rule. I appreciate your persistence here but I hope you can have some mutual appreciation for my stance.

Since Impreza is a paid theme and you're paying for it why not ask their assistance with this incompatibility?

**Comment by pakfones** [comment]
@thomasplevy 

**Great!** Thanks so much for your quick reply, **I get the point** if they can fix it then why i reply here? Because of you claim that LifterLMS also work on [Impreza](https://lifterlms.com/docs/impreza-theme-course-and-lesson-sidebar-compatibility/)  So installed and started. I thought that this will be helpful for others also.

Thanks again,

**Comment by thomasplevy** [comment]
@pakfones,

I've updated our documentation (removed it) that was a really old piece of documentation. I no longer attempt to maintain compatibility for 3rd party themes because it's too difficult for me to keep up with them and ensure a theme that LifterLMS worked with 18 months ago still works well together. Instead, we're working with theme developers directly to have them add compatibility for LifterLMS on their side. We have a ton of themes that natively support LifterLMS (some free) listed here: https://lifterlms.com/product-category/themes/

OceanWP also recently added LifterLMS support (and it's free) -- Astrid as well, I've heard, although I haven't tested that one yet.

If you've only just started you should be able to get a refund on Impreza and switch themes pretty easily.

I've tried to make compatibility simple through [Labs](https://lifterlms.com/docs/super-sidebars-lab/) and [this tutorial](https://lifterlms.com/docs/lifterlms-sidebar-support/). But it's not always that simple and sometimes there's gotchas that I can't anticipate.

I do my best to support our free users at https://wordpress.org/support/plugin/lifterlms but supporting premium themes and plugins is very difficult for me to do since, as I've noted, I can't run tests and debug these themes and plugins without purchasing them. I need to acquire copies and I cannot do that for all the themes. When dealing with our customers, we'll exchange zip files for the purposes of testing and debugging. It's, of course, easy to guess my email address and email me directly but, if I make a habit of responding to every user who uses LifterLMS and guesses my email address I will not have much time to get anything done and if I respond to emails for everyone it devalues the support I provide to our paying users. I cannot, do not, and will not budge on this. That does make me a rude and belligerent and stubborn in the eyes of some and I hold no grudge if you feel this way. 

I am very sorry if you took our advice and invested in Impreza based off that old integration guide. but despite this mistake that I've made, I still cannot assist unless you're willing to sign up for premium support, which is relatively inexpensive given the scope of what we offer to our users. Hell, instead of buying support, buy a product that you'll maybe use to make some money one day (like one of our integrations).

If you want to get premium support (or an add-on) and cannot afford it for whatever reason, we regularly offer scholarships, submit a request and we may be able to provide you a discount: https://lifterlms.com/scholarship-request/

Finally, please accept my apologies and I wish you the best of luck
