### ISSUE TITLE
Question about 2 Cookies LifterLMS uses

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#2329]
We had a customer ask:

_I'm using LifterLMS and I use CookieYes for gdpr compliant cookie notice.
LifterLMS seems to use 2 cookies **wp_llms_session_1ea71781820ba731c22da08aa1541bf0** and **llms-tracking**.

Can you give any futher information for what each of these cookies does?_

Is it possible to provide some info I can send to her about these 2 cookies and the purpose they serve?

**Comment by eri-trabiccolo** [comment]
Hey @willmiddleton-lifterlms 
Take a look a this:
https://github.com/gocodebox/private-issues/issues/62#issuecomment-1259845730

Basically:
1) `wp_llms_session` cookie is used for two main reasons:

  - to store the coupon at checkout - we leverage the session cookie so that if the user adds a coupon but doesn't buy the course then navigates on another page and comes back to the checkout the coupon it's still there.
  - to store notices for both logged in and logged out users. E.g. say you try to visit to a lesson which is for enrolled users only, we redirect you to the course page (or any other page - depends on whether the course has redirects for unrolled users) and show you the message restriction message. So what happens is that when you land on the restricted lesson, we check whether you can read it or not, set the notice in the session cookie, redirect you to the course page, where we look into the session cookie for the notice to display and display it.
  
  This cookie (^) lasts minimum 6 hours, but if the visitor is still active on the site after 5 hours the expire time is postponed of another 6 hours and so on.

2) `llms-tracking`, this cookie is set via js (and reset server side). **As of now** it's mainly used for the Advanced Videos add-on: it stores the video related events (start, pause, ecc) as a buffer prior to the dataset being sent to the server (n video completion). It's a _session_ cookie, meaning that expires when you close the browser.

Does this help?

**Comment by magicemilymiddleton** [comment]
Thanks! That's perfect
