### ISSUE TITLE
Do not re-add deleted "Mark Complete" button and the deleted lesson navigation when a lesson is edited in Elementor.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2440]
### Reproduction Steps

1. Install LifterLMS and Elementor. These must be the only two plugins installed.
2. Create a lesson in `WordPress Dashboard > Courses > Lessons > Add Lesson`.
3. Delete the `Lesson Progression (Mark Complete)` block in the Gutenberg editor.
4. Delete the `Lesson Navigation` block in the Gutenberg editor.
5. Click on `Publish`.
6. Visit the lesson front-end in a different tab. You will see that it does not have the `Lesson Progression (Mark Complete)` block and the `Lesson Navigation` block on the front-end.
7. Go back to the tab where you are editing the same lesson in the Gutenberg editor.
8. Click on `Edit with Elementor` (you don't even have to click on update).
9. Visit the lesson front-end in a different tab. You will see that it now has the `Lesson Progression (Mark Complete)` block and the `Lesson Navigation` block on the front-end.

### Expected Behavior
The  `Lesson Progression (Mark Complete)` block and the  `Lesson Navigation` block should not be re-added when you click on  `Edit with Elementor`.

### Actual Behavior
The  `Lesson Progression (Mark Complete)` block and the  `Lesson Navigation` block are re-added when you click on  `Edit with Elementor`. They only appear on the front-end, but not on the back-end.

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by dominiquemariano** [comment]
It appears that this issue is larger than reported. It also applies to other LifterLMS elements like the course information (e.g., course categories), course instructor, and course syllabus. Affected ticket is HS-217840.

**Comment by eri-trabiccolo** [comment]
Makes sense, they follow the same logic

**Comment by eri-trabiccolo** [comment]
@dominiquemariano 
Here's the explanation:
Prior to the Gutenberg introduction as default editor for WordPress there was what is now called "the classic editor". With the classic editor on, some elements (like the ones you cited above) were rendered/added to the course/lesson/membership and so on via action hooks "all around" the post type content.
When the Gutenberg was introduced we developed those "elements" as blocks and set them by default when creating a new course/membership/lesson etc. with the Gutenberg editor. When course/lesson/memberships use the Gutenberg editor those elements are then **not** rendered/added to the course/lesson/membership and so on via action hooks "all around" the post type content, they only display if the blocks are added to the content.
When you use the Divi/Beaver/Elementor builder, since you're not using the Gutenberg editor, we consider that as you were using the classic editor, because they're not the Gutenberg block editor. This means that for those post types built with Elementor those elements are rendered on front via hooks. That's by default.

So this is working as expected.
Actions hook callbacks can be removed via code, or, and that's the fastest/best way for non developers, using the LifterLMS Labs plugin: https://lifterlms.com/docs/lab-action-manager/


> Click on Edit with Elementor (you don't even have to click on update).

That's because as soon as you switch to Elementor, Elementor itself, even if you don't update, sets a post meta (so it saves something) to mark that post (course/lesson...) as "built with Elementor".
