### ISSUE TITLE
Investigate if there is a bug in the courses API.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2443]
### Reproduction Steps
ThriveCart can retrieve all the memberships correctly. However, it cannot retrieve all the courses consistently. **Sometimes it does**, but almost all the time it does not retrieve all the courses consistently. Is this correct?

### Expected Behavior
It must be possible to consistenly use our REST API to list out all the courses (or all the courses in a membership).

### Actual Behavior
Based on ticket HS-217590, the API results unreliable. Sometimes it works, but most of the time it doesn't work.

### This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
@dominiquemariano 
as you can see in our documentation: https://learn.femschool.de/wp-json/llms/v1/courses
the "list courses" endpoint can be reached at `<website-url>/wp-json/llms/v1/courses`

I could retrieve the courses list many times for the customer website. On our end I don't see any issues.

> Sometimes it does, but almost all the time it does not retrieve all the courses consistently. Is this correct?

Of course it's not correct, we don't set time/attempt limits.

Things to investigate:
1) What's the Thrive Cart request to retrieve the list of courses? This depends on **Thrive Cart**
2) Whether or not any PHP/server error happens when the courses list is not retrievable. (You already asked for debug log enabling)

**Comment by eri-trabiccolo** [comment]
@dominiquemariano 
any news on this?

**Comment by eri-trabiccolo** [comment]
Gonna close this, please re-open if you have new information @dominiquemariano
