### ISSUE TITLE
Date that the user started and completed the course

### ISSUE THREAD

**Issue by maustange** [gocodebox/lifterlms#2503]
How to print the date the user started and completed the course on the certificate.

**Comment by eri-trabiccolo** [comment]
Hi @maustange 
this looks more like a support request, although since currently there's no shortcode/merge code that would allow you to do that easily, you might need to write some custom code yourself or hire [an expert](https://lifterlms.com/experts/). 

GitHub is NOT a support form! If you require user support with LifterLMS you will have more success in one of the following places:

- Support Forums: https://wordpress.org/support/plugin/lifterlms
- Official Support Tickets: https://lifterlms.com/my-account/my-tickets
- LifterLMS Community Slack Channel: https://lifterlms.com/slack

That said, certificates are generic and can be issued for various reasons/events. Even the concept of "user started a course" is not immediate in LifterLMS, you can have when the user has been enrolled in a course, or when completed the first lesson (the latter requires a custom sql query), and so no.

About the completed data, if you issue the certificate on a course completion event, well the earned date is actually the course completion data: `{earned_date}`. Hope this helps.
