### ISSUE TITLE
Previous / Next Lessons Navigation

### ISSUE THREAD

**Issue by sujaypawar** [gocodebox/lifterlms#415]
If the short description is little too long, it affects the design of the navigation. I see there was an option to disable the excerpt, but it is deprecated now. 

Screenshot - https://cl.ly/112X2A2o1A0i

- Was there any reason for this for deprecating it? 
- Would you recommend a theme provide option for such design control?

**Comment by thomasplevy** [comment]
> Was there any reason for this for deprecating it?

We removed several dozen options implemented via the `wp_options` table during our 3.x update in order to reduce the number of database calls made by LifterLMS during page loads. I replaced each of these options with filters. If you want to disable the excerpt you can use the filter [llms_show_preview_excerpt](https://lifterlms.com/docs/lifterlms-filters/#llms_show_preview_excerpt).

> Would you recommend a theme provide option for such design control?

Yes, I would. It's hard to decide *what* LifterLMS should be responsible for and what a theme should be responsible for but the longer we work on LifterLMS the more we realize the importance of allowing themes to focus on design and interface. I'm working more and more to simplify the design, css, and so on; to remove settings in favor of showing all LifterLMS can do and if you don't like it, customize it. We're building a general plugin that should work generally well with as many themes as possible but I realize that's actually kind of a lie. The themes need to do work because I simply *cannot* write CSS and interfaces that actually look good inside any theme. Please make some choices as the theme dev!
