### ISSUE TITLE
JS Error in Console

### ISSUE THREAD

**Issue by sujaypawar** [gocodebox/lifterlms#423]
I often see this error in console on course catalogue page and though I should report.

Here is the screenshot: https://cloudup.com/cHgv6ODfrgp

**Comment by thomasplevy** [comment]
ill look into this... I haven't spent much time working inside the customizer with LifterLMS as we don't actually customize anything in the plugin via the customizer so it's not an area I test regularly

**Comment by thomasplevy** [comment]
@sujaypawar I'm not seeing this error reported on the catalog when I load up the customizer.

This may be related to the "janky" asset loading we're doing to ensure dependencies are properly loaded: see #146 where this issue was raised a while ago... 

This is a large refactor that needs to be taken on to truly rework our asset pipeline.

In the meantime I don't think this is a critical bug -- but possibly just an annoying one...

If you want me to continue investigating I'll need more recreation info so I can figure out how to reliably reproduce and debug.

See the contribution guidelines for that information that I'm looking for

**Comment by sujaypawar** [comment]
No worries Thomas. You can close this one.
