### ISSUE TITLE
5.4 "Can't use method return value in write context"

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#437]
Update functions using `empty()` to evaluate function returns to prevent php 5.4 issues despite LifterLMS's official 5.6 or higher PHP support

Alternatively prevent LifterLMS from running at all using a PHP version check during plugin initialization....?

**Comment by actual-saurabh** [comment]
Since [PHP 5.6 is not actively supported anymore](http://php.net/supported-versions.php) and even the security support would stop later this year, I suppose one can be bold enough to not support versions below 7.0 and refuse to load LifterLMS on lesser versions.

Syntactically, all 7.0 code should work perfectly on 5.6 and supporting lower versions has the potential side-effect of unnecessary and unpredictable support issues and unknown security vulnerabilities.
