### ISSUE TITLE
Yoast Seo description not used in Course-Catalog

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#457]
### 1. Reproduction Steps

* Install Yoast SEO
* Set a description in the metabox of yoast on the `course-catalog` page
* check the html source of that page

### 2. Expected Behavior

* Show the meta description with the custom test

### 3. Actual Behavior

* Yoast seems not executed

I think that is a bug of Lifter because with the other pages of the website works without issues. Probably because this page is changed by the plugin.

**Comment by thomasplevy** [comment]
Hey @Mte90,

This isn't a bug exactly and it's a bit of a complicated problem that I don't believe LifterLMS is going to attempt to solve in the core codebase... here's why (and I'm open to alternative suggestions and discussion)

1. The course & membership catalog __pages__ act as placeholders (of sorts) for the custom post type archive for the `course` and `llms_membership` post types respectively. As such, the *content* found on the page itself isn't the actual content of the page, but the "loop" is.  The title and slug of the page are pulled. The page id is used in various core functions for easy linking. If you add content to the page WYSIWYG editor it displays above the loop (allows easily adding custom content before the loop like "HEY HERE'S MY COURSES" or whatever... 

2. This functionality is largely the same as how WordPress handles the "Blog" page in the WordPress core. (Excluding the content part that we added because we see a lot of users wanting to easily add content before the loop).

3. Yoast outputs its metabox on all pages and Yoast is not itself aware that any of this custom functionality is happening. So yes the content added there does not execute on the frontend. It seems like a LifterLMS bug but we could argue from a different perspective that it's a Yoast bug. I wouldn't actually call it a bug in either software. It's a compatibility issue.

4. Yoast *does provide* functionality to control the custom post type archive SEO information. Head to SEO Settings -> Titles & Mets -> Post Types & scroll to the Custom Post Type Archives section. You can configure your SEO settings for course & membership catalog pages (and for course and membership taxonomy archive pages) here.

All this begs the question: Is this *our* responsibility or Yoast's responsibility?

This seems like the kind of thing that easily can be ignored once you know how it works and we can move on.

I don't feel it's something that LifterLMS should actually add to the LifterLMS core. If we do that then we will be obligated to add support for other SEO plugins. I've moved away from adding too much third party support directly to LifterLMS as I end up running into too many maintenance issues. I make exceptions when there's obviously a bug or conflict. This, however, isn't exactly a bug. It's more nuanced, and it doesn't feel like something I should be adding support for because it relies mostly on me using filters from Yoast or disabling Yoast functionality...

Furthermore, lets look to giants: roll up a WooCommerce site and experience this exact behavior on the shop page... That doesn't exactly mean that I'm correct, but I do take nods from those who have much larger and mature codebases. WooCommerce doesn't add a lot of third party support like this and I imagine it's because the compatibility issues become difficult to maintain over time.

Thoughts?

**Comment by Mte90** [comment]
Uhm maybe the best way it is to use `the_content` filter in that way only the content is changed and not create conflict with Yoast (that put stuff in the `head`).
In that filter a check about if it is a `page` post type and next inject the loop or whatever.
Maybe add an integration for yoast to alert about this issue can be also another issue.

**Comment by thomasplevy** [comment]
We'll agree to disagree on this. I'm not going to rework the way we do things here (we're following a well established pattern in WordPress plugins) and I'm not going to build a custom Yoast integration.

Please use the custom post type archive settings.
