### ISSUE TITLE
Performance issues on course page

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#461]
We have issues on performance mainly for the huge numbers of query that lifter is doing.
If you go on https://skillsandmore.org/corso/installa-gestisci-genesis-pro/ as example you can see that also with a CDN for static assets and W3TC the page is very slow on generating the html.

Analyzing with a profiler we see that:

![a205e881-dc9b-41ed-b69f-cd72e7e999e0](https://user-images.githubusercontent.com/403283/36667048-e254d34a-1aec-11e8-913f-5f0488624e06.png)

The profiler not reconize correct the plugin (mark everything as by the theme `skam-2017` made with genesis).
Looking at the code of the template file mentioned in the screen there are only few tweaks to change the title.
Seems that in any case for every lesson lifter do a query for the custom meta, it's not better to do a transient for every single course view?
In that way the output for this info is less?

**Comment by Mte90** [comment]
I see also with a plugin that use a post type called in a single page post type of lesson this:
```
SELECT wp_posts.* FROM wp_posts WHERE 1=1 AND wp_posts.ID NOT IN (17014) AND wp_posts.post_type = 'glossary' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'closed' OR wp_posts.post_status = 'llms-completed' OR wp_posts.post_status = 'llms-active' OR wp_posts.post_status = 'llms-expired' OR wp_posts.post_status = 'llms-on-hold' OR wp_posts.post_status = 'llms-pending' OR wp_posts.post_status = 'llms-cancelled' OR wp_posts.post_status = 'llms-refunded' OR wp_posts.post_status = 'llms-failed' OR wp_posts.post_status = 'llms-txn-failed' OR wp_posts.post_status = 'llms-txn-pending' OR wp_posts.post_status = 'llms-txn-refunded' OR wp_posts.post_status = 'llms-txn-succeeded') ORDER BY (LENGTH(wp_posts.post_title) - LENGTH(REPLACE(wp_posts.post_title, ' ', ''))+1) DESC ```

Seems that in `wp_query` also for post type that are not of lifterlms is appended the custom status so maybe it is possible to avoid that.

**Comment by thomasplevy** [comment]
yes.

See #393 & #403 pending issues related to the symptoms you're seeing.

I apologize for these inefficiencies. There's a major refactor overdue to optimize these queries.

**Comment by Mte90** [comment]
Actually this is a big problem for us, how I can help you on fix this issues?
Maybe I can start to work on https://github.com/gocodebox/lifterlms/issues/461#issuecomment-368469015 that seems not so difficult and easy.

**Comment by thomasplevy** [comment]
@Mte90 you're welcome to submit any pull requests you'd like. If it's not obvious to you (as I'm sure it is). I'm the only full time dev and there's many more requests, issues, and bugs than I can process in the necessary time frame... I'm sorry that this is a major issue for you and I'm sorry I haven't solved it yet... If you want to work on it please do.

**Comment by Mte90** [comment]
The issue I was talking to fix is not something fault of this plugin but a normal behaviour of wp_query, when the wp_query doesn't define the post status use any so any post status is define in the query itself.
I will try to work on something else to do for performance in this plugin.

**Comment by Mte90** [comment]
I am trying to understand why there are a lot select of meta of the same post id. Maybe they are not cached and this is easy to fix.

**Comment by thomasplevy** [comment]
> I am trying to understand why there are a lot select of meta of the same post id. Maybe they are not cached and this is easy to fix.

Shortsighted programming -- see #393 -- the get_progress is an extremely inefficient function. Since the catalog has progress bars this is called a lot...

**Comment by Mte90** [comment]
2 pr for you to analyse :-)
In any case seems easy to fix this performance issue with a caching inside the class or a meta (depends on case).

**Comment by thomasplevy** [comment]
@Mte90 have a look at the update I pushed to the [student-progress](https://github.com/gocodebox/lifterlms/compare/student-progress) branch.

This adds 2 changes:

1. the `is_complete()` function no longer users `get_progress()`. Instead it looks up the completion status on the user_postmeta table. This *does* mean there's still a database call but on course catalog pages for sites with large courses (lots of sections and lessons) it's far fewer database calls. Calling the database is inevitable but this should be much more performant than previously.

2. The `get_progress()` function adds a caching option. Cached data is stored on the user meta table and cleared whenever progress is updated. The progress will be regenerated next time it's requested so that does mean that on a site with no cached data there will be a "ramping" period while progress is regenerated and added to the cache on the usermeta table. Theoretically we could add a script that "primes" the cache in the background but I'm not going to mess with that today.

Additionally, progress cascades up to it's parent. The only things ever marked as complete / incomplete in LifterLMS are lessons and when that happens the lesson checks the section's progress and marks the section complete (if it is) and then the section checks the course and the course checks the track... That means that the progress of all of these things will be cached independently and this means that the size of the usermeta table increases potentially by a lot as a result of having all these new records added... I considered adding this all as a serialized array as one item on the user meta table but that adds a slowdown when calling data from the cache since you know need to get the cache, unserialize, check for your object and then you need to do the same when clearing. I think having a larger database is preferable to the performance issues of dealing wit that serialized data.

Please have a look at this and let me know if this is a step in the right direction.

It passes all our unit tests but I haven't actually run any live tests on a site as a real user..

**Comment by Mte90** [comment]
I am using this branch on our production website, fro mthe first test I see that the page ism ore fast then before.
We need to check that at the end of the day to understand the stress on the server.
In any case seems that there are less query to the db.
I am waiting to add the profiler and check what's up like for the first comment :-)

**Comment by Mte90** [comment]
https://screenshots.firefox.com/fJFUK7KVhAuhB9Kx/web25.keliweb.com
This are the last 24 hours, I loaded the branch 4 hours ago.
As I can see there are improvements but they are not enough in our case. I cannot enable the profiler for exhausting resources right now, I will keep try to do it in the next hours.

**Comment by thomasplevy** [comment]
@Mte90 can you post a system report or at the very least the system specs of your server for me.

I do realize there's a lot of database calls here but I'm a bit stumped how to further reduce the number of database calls.

Additionally, I do see this is a customized template, could you share that template with me as well please.

Thanks

**Comment by Mte90** [comment]
Looking our stats seems that is not enough.

Query on archive page of courses
![screenshot-2018-3-2 archivi corsi - skillsandmore](https://user-images.githubusercontent.com/403283/36915565-74895864-1e51-11e8-89f6-7989a4096cc5.png)

Query on a course, I can see the same query multiple time
![screenshot-2018-3-2 crea i nuovi layout con flexbox](https://user-images.githubusercontent.com/403283/36915631-b269adfa-1e51-11e8-89d3-db35dd51dd42.png)

I cannot enable the advanced profiler for resources, I will try later on night when the website is more relaxed.

**Comment by Mte90** [comment]
![screenshot_20180305_184733](https://user-images.githubusercontent.com/403283/37029770-da0270c4-2138-11e8-95a4-e43c70baf2f1.png)
![screenshot_20180305_184838](https://user-images.githubusercontent.com/403283/37029771-da25a8aa-2138-11e8-881c-92fcceb1ffc8.png)

Just as other reference is our page with the student branch in production, with logged users we disabled the page cache.
As you can see the difference of time of loading of the page, we are using also a CDN.
Every optimization of queries in the page for us is a lot. At least evaluate the support for caching of query output. As I can remember if it is used wp_query with their parameters wordpress will cache that with the plugin for cache but when are custom query is not.

**Comment by Mte90** [comment]
I know, you already explained :-0, there is something that I can do for help you on that?
I am not an expert of this code so if you can help on that I will try to do something :-)

**Comment by thomasplevy** [comment]
I don't exactly know where to start on all this... I really don't... If I had a solution I'd have written it already...

I know that LifterLMS *does a lot of stuff* but I truly don't know how to fully solve the optimizations you're noting... LifterLMS saves data to the database and displays it on screen... I'm sure theres better ways to do everything but I'm not sure how to this...

Saying "cache things" is easy but writing code that actually optimizes and doesn't cause issues across the entire user base is more complicated... I'm sorry but I don't have any direction to point you in at this moment...

You keep saying "Cache things" so maybe write code that caches things... I'm not sure...

**Comment by thomasplevy** [comment]
Further improvements can still be made here but #474 & #393 are now closed and should resolve a significant portion of the issues raised here.

Should I close this out @Mte90 or are there other items here I'm missing yet?

**Comment by Mte90** [comment]
I think that we can close and if I will find something else I will open a new ticket :-)

**Comment by thomasplevy** [comment]
@Mte90 happy to close!
