### ISSUE TITLE
These query happens in all the pages

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#514]
![immagine](https://user-images.githubusercontent.com/403283/39398914-2fccd548-4b15-11e8-8a54-a73f5141591d.png)
This are the queries that happen in all the pages (in this case in the website homepage) maybe we can do something to do only when required?

**Comment by thomasplevy** [comment]
Cert options should not be being autoloaded, yes... I'll have to figure out how to adjust that

`lock_down_admin` I think was removed a long time ago and replaced with a filter, I don't think it actually serves a purpose anymore and is probably a missed line during refactors (sorry)

`shop_page_id` may be a little more difficult to exclude as I need to spend some time testing the consequences of making that unavailable. It's used by menu items I think which means that we may need to assume that it's going to be used... but maybe I'm wrong about that. I need to run some test cases on it and see.

**Comment by Mte90** [comment]
Well atleast remove a query in the meantime is not bad :-D
Maybe for the shop id will be useful https://github.com/gocodebox/lifterlms/issues/473

**Comment by thomasplevy** [comment]
Related #513

**Comment by thomasplevy** [comment]
@Mte90 maybe you're still interested in this

+ `lifterlms_lock_down` -- removed in LifterLMS 3.27.0 (forthcoming), replaced with a filter. This option has never been "settable" via a settings panel so having it as an option is bloated.
+ `lifterlms_logout_endpoint` -- no longer exists in the codebase. This must have existed at some point in the past and was likely an option set with "autoload = yes"; to remove this head into your database and simply delete the option
+ `lifterlms_certificate_bg_img_height` & `lifterlms_certificate_bg_img_width` -- these are both used to generate a custom image size (see code [here](https://github.com/gocodebox/lifterlms/blob/master/includes/functions/llms.functions.certificate.php#L107)) removing these options would mean that we'd no longer allow users to customize an important aspect of their certificates. I did a little digging and I cannot find a reliable way to disable the necessity of adding the image size on all page loads as it's recommended to run this on the `after_theme_setup` hook. If this is causing you great stress or performance issues you should remove the function adding the image sizes with `remove_action( 'after_setup_theme', 'llms_register_certificate_image_size' );` and you can then replace this function with a duplicate that has your sizes hardcoded into it instead of relying on an option. Knowing the performance impact today leaves me feeling that these should actually not be options but if I take these options away today I'm sure there will be many support requests which will result in us having to write custom code snippets to customize these sizes. It is an option and it'll have to stay an option for now. Sorry.
+ `lifterlms_llms_shop_page_id` -- I do not see this option anywhere in the codebase nor do I see it in my testing database. I'm not sure where this is coming from or why. The option seems like it's supposed to be `lifterlms_shop_page_id` which is the option used to determine which page is the course catalog page but it's not that exactly. If you have any ideas about this let me know below.

The other queries look pretty standard.

I'm marking this as resolved based on changes and findings but if you have further questions please respond and let me know
