### ISSUE TITLE
Style Cascade Order is incorrect in certificate export

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#558]
This part of the certificate export removes all link tags and converts them into style tags that are appended at the end. 

https://github.com/gocodebox/lifterlms/blob/d04671439f66f15668ff71cbd706dcfc35d79673/includes/class.llms.certificates.php#L178-L213

It doesn't accomodate the particular order in which stylesheets added through the link tag and through inline style tags are loaded for the actual results. So, a lot of custom CSS becomes ineffective and the export looks different from how the certificate appears on the website.

Instead if the link tag is replaced exactly in the same position using http://php.net/manual/en/domnode.replacechild.php, the order would be maintained.

**Comment by thomasplevy** [comment]
Can you provide a specific example of a link losing it's initial order during the loop? The getElementsByTagName seems to be loading them in their initial order and then during the loop they're all appended in the same order so I don't see the order changing here (I did a quick comparison).

I wouldn't care but see the my note on #559 which has me questioning this issue now

**Comment by actual-saurabh** [comment]
I missed the removal of non `rel="stylesheet"` link tags.

So, the line that removes all the link tags should still exist (I'll update the PR accordingly)

What is causing an issue is that the order of inline `style` tags. If inline css is added after a stylesheet is loaded:

```
<link rel="stylesheet" href="some_stylesheet_url.css">
<style>
/* contains definitions that override styles in `some_stylesheet_url.css`
</style>
<link rel="stylesheet" href="another_stylesheet_url.css">
```

After processing, this becomes *equivalent* to:
```
<style>
/* contains definitions that override styles in `some_stylesheet_url.css`
</style>
<link rel="stylesheet" href="some_stylesheet_url.css">
<link rel="stylesheet" href="another_stylesheet_url.css">
```

because all the link tags are replaced and appended at the end, breaking the order between inline styles and link tags.

**Comment by thomasplevy** [comment]
I figured out what I was seeing...

After some debugging I found that on my test site there would be 27 `<links>` to be replaced or removed but only the first 21 links would actually be updated resulting in missing styles. Mysterious.

I found this comment in the php docs: I found the following on PHP.net: http://php.net/manual/en/class.domnodelist.php#83178

The original code did not modify the dom with relation to the list of elements found in the `$links` variable but by using replace child links would be removed during iteration. This caused some links to get missed completely (and therefore they weren't getting inlined). After your update to remove other links it also meant they would just completely dissappear.

So I modified again. Updated PR creates a list of replacements to be made. Runs another loop at the end to make those replacements and then removes all remaining links using the while loop.

This seems like a ton of looping but I couldn't find a way to make it work otherwise.

I think this resolves it now.
