### ISSUE TITLE
Loop overrides any category description with post content of the Course/ Membership page

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#581]
https://github.com/gocodebox/lifterlms/blob/baa037bdcbf6fa3dc1666ceed55edcf51a3453d7/includes/functions/llms.functions.templates.loop.php#L10-L40

The term description is never displayed. 

@thomasplevy Can this be replaced with a check for term description and only when it is empty, override it with the post content, as it is done now?

**Comment by thomasplevy** [comment]
> Can this be replaced with a check for term description and only when it is empty, override it with the post content, as it is done now?

I don't see any particular issue with that

**Comment by BurlesonBrad** [comment]
Thanks

**Comment by thomasplevy** [comment]
@BurlesonBrad I think you may be misunderstanding this issue... or maybe I'm misunderstading your question.

The proposed update would allow you to define custom content for each category that would be displayed above the default list of items.

Currently you can add content to your catalog page (the actual WordPress page) and that content will be output **before** all the items in the catalog. This allows you to add a descriptive paragraph, add an image, whatever, and then the list of products is listed below that.

What @actual-saurabh has suggested is to run an additional check when a catalog page for a course/membership category to see if there is a category description saved for the current term. If there is, display that in place of catalog page's content above the list of items. This would allow you to define custom content on the top of each category instead of only having one option (the content from the catalog page itself).

Currently course category pages actually work just fine and "house" all the courses categorized in the specific category and you can add *anything with a url* to your menu already as well.

If you want the course category you've identified in your comment in your navigation menu you can do that today without us adding what @actual-saurabh has suggested here.

Looking at the link you provided it seems to be that the category page is displaying only items from that category effectively housing them as it should. If you're seeing different behavior please provide some clear reproduction steps in a NEW ISSUE or (even better open a support ticket) so we can investigate that issue specifically.

**Comment by BurlesonBrad** [comment]
sorry. lemme specifiy a bit clearer.  _(fyi: as of this second - I was messing with Elementor)_
It's the /course-category/ **Description** area that wasn't displaying in LaunchPad when the /course-category/ url was viewed.

In other words, using the URL above as an example:
When viewing the `taxonomy=course_cat` , if a user has added something like this _(again, just an example)_ to the **Description** area:
![image](https://user-images.githubusercontent.com/6208757/41067095-efd5b96a-69a9-11e8-8be3-ab33059b5df7.png)
....then the **Description** content which the user has entered content should be displayed 👍 

` <?php echo category_description( $category_id ); ?>`

**Comment by thomasplevy** [comment]
@BurlesonBrad,

You're correct. Your initial comment seemed to be pointing to a bug report of something completely unrelated to this so I wanted to ensure if you were asking about something else that didn't go ignored.

This is exactly what you're looking for per this latest comment.
