### ISSUE TITLE
PHP Warning: Division by zero - when getting section's, with no completed lesson, percentage of completion

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#631]
### 1. Reproduction Steps
I'm using a simple instruction to retrieve a LLM_Section's percentage of completion value in a template, e.g. in [course/syllabus.php](https://github.com/gocodebox/lifterlms/blob/master/templates/course/syllabus.php#L31-L32)  : 
```php
		<?php foreach ( $sections as $s ) :
			$section            = new LLMS_Section( $s->ID );
			$is_complete        = 100 === (int)$section->get_percent_complete();
		?>
```

### 2. Expected Behavior
I would expect to retrieve the percentage of completion without any PHP warning when a section has no completed lesson.

### 3. Actual Behavior

When a section has no completed lesson I get a _Division by zero_ PHP warning.

### 4. Error Messages / Logs

`[29-Aug-2018 10:07:37 UTC] PHP Warning:  Division by zero in /srv/www/XXXX/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.section.php on line 408`

**Comment by thomasplevy** [comment]
@eri-trabiccolo thanks for raising the issue and the PR

I'm going to take this as an opportunity to get a few tests written for the class methods in question and will merge it in shortly.

Thanks!

**Comment by thomasplevy** [comment]
@eri-trabiccolo after some review turns out that we've been lazy on refactoring this class to use some improved methods... I rewrote your PR (sorry) but it fixes this issue and also increases the performance by using WP object caching as well.

The `get_percent_complete` method is now using `LLMS_Student::get_progress()` 

https://github.com/gocodebox/lifterlms/blob/master/includes/models/model.llms.student.php#L1005

Which does take this division by zero into account.

In any event no changes should be necessary to your above code example and the warning will no longer be generated (as expected).

This will be available in 3.23.1 and that should be available publicly sometime in the next few days.

Thanks again!

**Comment by eri-trabiccolo** [comment]
@thomasplevy many thanks for taking the time to share this explanation with me.
About the PR rewrite: no need to be sorry at all of course! My main goal was to inform you about the issue and help with a basic solution according to my understanding ;)

Also thanks for adding me as contributor, even if I didn't do that much.

Keep up the good work!

**Comment by thomasplevy** [comment]
@eri-trabiccolo Of course! I get a little controlly sometimes and I just wanted you to know why I discarded your code in favor of my own!

And of course, credit where credit is due. I didn't know this was an issue and you helped fix it so thank you so much!
