### ISSUE TITLE
Custom post types should be displayed in REST API for Gutenberg

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#662]
add `show_in_rest` to post types (courses, lessons, memberships) during post type registration

this change should be able to be made immediately without concern for other Gutenberg issues.

- [ ] Course
- [ ] Lesson
- [ ] Membership

Other post types could be exposed in rest in the future but for immediate purposes I believe these are the only post types that would require rest support to support Gutenberg

**Comment by AndreaBarghigiani** [comment]
Hi @thomasplevy,
I would like to start to work on this issue but on the way approaching it I had a doubt.

Some of your CPT have a dirrefent case uses and I would like to clarify which of them should be exposed via REST API, at least for the use in Gutenberg.

I think that CPT as *Memberships*, *Courses* and *Lessons* are the only one that should use Gutenberg because others CPTs in most of them the UI has been created to serve a single scope.

Maybe I sould consider also *Email* but I think will be really difficult use the Gutenberg code in a template email.

**Comment by thomasplevy** [comment]
@AndreaBarghigiani for the initial purposes I agree: courses, lessons, memberships

Updated the issue accordingly.
