### ISSUE TITLE
Set admin that receive email notification

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#766]
**Is your feature request related to a problem? Please describe.**
I am managing a website for a customer and both of us are admin of the website.
THe problem is that both of us receive email notification from Lifterlms about people that buy the course etc.

**Describe the solution you'd like**
Set who is the admin that will receive notifications

**Describe alternatives you've considered**
Right now I configured my email server to put in the trash all the email from that website but is not a good solution.

**Comment by thomasplevy** [comment]
@Mte90,

The *admin* doesn't receive notifications, the course instructor does. You can configure this already for each notification under the "Subscriber" settings for the notification.

By default LifterLMS only sends to the primary instructor (this is the first instructor in the list) & the instructor set as the "author" of the course.

My guess is that you're also receiving these due to CC settings on the notification.

Head to LifterLMS -> Settings -> Notifications and click "Email" for the notification(s) you'd like to configure then find the "Subscriber" settings and adjust accordingly. If you don't want the primary instructor to receive the emails, then uncheck the author checkbox and you can configure specific emails in the field for adding subscribers.

Let me know if that helps

**Comment by Mte90** [comment]
You are right seems that my account was the course author but shouldn't be configured in that way.
I am changing the author :-)
