### ISSUE TITLE
Mark Complete button displayed outside of lesson causes fatal error

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#775]
### 1. Reproduction Steps

+ ~Add a mark complete button to a course (or page or post or anything other than a lesson) `[lifterlms_lesson_mark_complete]`~
+ Add a Lesson Progression block to a course post type [updated 5/16]

### 2. Expected Behavior

+ Mark complete button shouldn't render

### 3. Actual Behavior

+ 500 error encountered

### 4. Error Messages / Logs

```
[28-Feb-2019 17:17:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method LLMS_Course::has_quiz() in ***/wp-content/plugins/lifterlms/includes/functions/llms-functions-progression.php:61
Stack trace:
#0 ***/wp-content/plugins/lifterlms/includes/functions/llms-functions-progression.php(42): llms_show_take_quiz_button(Object(LLMS_Course))
#1 ***/wp-content/plugins/lifterlms/templates/course/complete-lesson-link.php(70): llms_show_mark_complete_button(Object(LLMS_Course))
#2 ***/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(84): include('***/...')
#3 ***/wp-content/plugins/lifterlms/includes/llms.template.functions.php(356): llms_get_template('course/complete...')
#4 ***/wp-includes/class-wp-hook.php(286): lifterlms_template_complete_lesson_link('')
#5 ***/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 ***/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 ***/wp-content/t in ***/wp-content/plugins/lifterlms/includes/functions/llms-functions-progression.php on line 61
```

**Comment by eri-trabiccolo** [comment]
A couple of considerations/questions about this:
1) > Add a mark complete button to a course (or page or post or anything other than a lesson) 

Actually when added to anything that is not a LLMS post, the shortcode behaves as expected, as far as I can see, as the following check is matched:
https://github.com/gocodebox/lifterlms/blob/3.30.2/templates/course/complete-lesson-link.php#L16
no button is displayed and no error is triggered.
Right? I'm asking because if I'm wrong this means that I've been not able to reproduce all the conditions in which this issue occurs.

2) As per the [shortcode documentation](https://lifterlms.com/docs/shortcodes/#lifterlms_lesson_mark_complete) itself:

> Must be used on a LifterLMS Lesson!

And I think it makes sense, the whole template's code "expects" a lesson there, my idea then is to check on if `is_lesson()` very early, but still in the template.

I'm going to make a PR.

3) [side note] The documentation also says:

> If you’re an admin and not enrolled the button will not display!

Actually this is not true, as, if I am an administrator I can edit the lesson, hence `! current_user_can( 'edit_post', $lesson->get( 'id' ) )` is false and the whole condition here:
https://github.com/gocodebox/lifterlms/blob/3.30.2/templates/course/complete-lesson-link.php#L20
 doesn't match and I will see the button.

Am I wrong?!
If not, an issue should be opened about this, but I'm not sure whether the latter is the expected behavior and the documentation is wrong or rather the opposite :D

**Comment by thomasplevy** [comment]
I've updated the recreation steps here. The issue arises when a lesson progression block is added to a course only. The original recreation steps were invalid.

Closing #829 as it doesn't actually solve the issue. This issue will be resolved by https://github.com/gocodebox/lifterlms-blocks/issues/20 (which is now possible to resolve thanks to filters added in the WP Core)

**Comment by thomasplevy** [comment]
Okay #829 was part of the fix, resolved now via https://github.com/gocodebox/lifterlms/commit/9324bbd7bc3a92d29b5fa839c12454e6c5a8077a
