### ISSUE TITLE
Access Plan "Description" misbehaves when a "Classic" block exists on a course or membership

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#777]
### 1. Reproduction Steps

+ Create a course
+ Add a "Classic Editor" block to it
+ Create an access plan
+ Save the course / access plan

### 2. Expected Behavior

+ Everything should be fine

### 3. Actual Behavior

+ The content from the Classic Block is pushed into the TinyMCE editor on the access plan

**Comment by eri-trabiccolo** [comment]
Had to dig a little bit in order to find at least the piece of code that generates this conflict.
It turned out to be this:
https://github.com/gocodebox/lifterlms/blob/3.36.2/assets/js/llms-metabox-product.js#L768

Or better, the "couple":
https://github.com/gocodebox/lifterlms/blob/3.36.2/assets/js/llms-metabox-product.js#L755
and
https://github.com/gocodebox/lifterlms/blob/3.36.2/assets/js/llms-metabox-product.js#L768

I'm not entirely sure what that line of code triggers somewhere else to generate such an issue but it does.
The `update_plan_orders()` method is called multiple times: either when saving the access plans but also when creating a new one or reordering them. In fact you should be able to reproduce the same issue even just re-sorting two access plan.
_[Note: this issue affected also courses built with the Elementor builder as, the whole Elementor content results in a Classic Editor block (although hidden via CSS) when a post is edited with the block editor]_

I've explored various ways to keep the current functionality of the access plan editor (which at the moment is not perfect and we should think about an overhaul as the Text mode loses the toolbar when reordering/saving, basically when it's re-inited), and come up with what I call a "whatever works" solution.
I call it this way because I don't know exactly why it works better than the previous solution, but it doesn't seem to introduce any regression and fixes this very issue.
I don't like these kind of no-reason solutions, but with my current understanding of the whole metaboxes js and the tinymce js itself this is the best I could come up with at this stage, so feel free to not accept the PR or request changes or request trashing an burn it while laughing at it :D

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

> I've explored various ways to keep the current functionality of the access plan editor (which at the moment is not perfect and we should think about an overhaul as the Text mode loses the toolbar when reordering/saving, basically when it's re-inited), and come up with what I call a "whatever works" solution.

Yep. I agree. I'd like to ditch the metabox all together and allow access plan management via a block editor "plugin" which will allow plans to be managed in a modal overlay. See gocodebox/lifterlms#2061

If you have a easily accessible Yoast install they've moved their snippet editor metabox into the block editor sidebar/modal combination and it's real slick. Of course it doesn't handle classic. When we get this "fixed" it'll be "this is kind of wonky on classic and flawless on the block editor" and we'll just ride out tinymce wonkiness until classic is officially abandoned *sigh* 2022?

**Comment by eri-trabiccolo** [comment]
@thomasplevy
Yeah I saw Yoast SEO.
I'm with you about the _sigh_ but given how the block editor evolves maybe 2030.

**Comment by thomasplevy** [comment]
@eri-trabiccolo could you update the support ticket related to the Elementor aspect of this issue and let the user know this has been resolved in 3.36.3.

Thanks!

**Comment by eri-trabiccolo** [comment]
done
