### ISSUE TITLE
Programmatic reset password keys fail with LifterLMS reset-password form

### ISSUE THREAD

**Issue by andrewvaughan** [gocodebox/lifterlms#846]
LifterLMS has implemented its own version of the WordPress forgot password functionality that is no-longer compliant with the WordPress core system.  This prevents any additional plugins that generate reset password keys programmatically from working.

Specifically, WordPress' built-in `get_password_reset_key()` is not compatible with LifterLMS' reset password functionality, as WordPress has been changed to include a timestamp in the database as part of the key, and Lifter does not check this.

LifterLMS should ideally use WordPress' built-in `get_password_reset_key()` functionality instead of generating its own key, allowing it to work with other plugins and login-based functionality.

### Reproduction Steps

To reproduce, generate a forgot password URL for LifterLMS using WordPress' functionality:

```php
$resetKey = network_site_url(
        "/dashboard/forgot-password?key=" . get_password_reset_key($user) . "&login=" . rawurlencode($user->user_login),
        'login'
);
```

This URL will fail with the message `Invalid key`, as the database includes a timestamp from the `get_password_reset_key()` method that is not checked in LifterLMS here:

https://github.com/gocodebox/lifterlms/blob/f93a34750bfc8b2390239129a112fb5f3686b43d/includes/llms.functions.core.php#L1027

Point in WordPress code where the timestamp is included:

https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-includes/user.php#L2342

### Expected Behavior

LifterLMS should accept keys generated by WordPress for resetting password keys.

### Actual Behavior

Lifter returns an error from this line, specifically because the timestamp interferes with the check:

https://github.com/gocodebox/lifterlms/blob/f93a34750bfc8b2390239129a112fb5f3686b43d/includes/llms.functions.core.php#L1030

### Error Messages / Logs

N/A

### System Information

<details>
<summary>System Report</summary>
  
N/A

</details>

### Browser, Device, and Operating System Information

WordPress Docker image; latest.

**Comment by thomasplevy** [comment]
It looks like we built our own because the `get_password_reset_key()` function didn't exist when we launched. I wasn't aware that this has been decoupled from the core password reset form. Now that it is we can certainly update accordingly so that you can use your own keys generated by the WP core function.

+ `llms_verify_password_reset_key()` ([link](https://github.com/gocodebox/lifterlms/blob/f93a34750bfc8b2390239129a112fb5f3686b43d/includes/llms.functions.core.php#L999)) should use core `check_password_reset_key()` ([link](https://developer.wordpress.org/reference/functions/check_password_reset_key/))
+ `llms_set_user_password_rest_key()` ([link](https://github.com/gocodebox/lifterlms/blob/3.30.0/includes/functions/llms.functions.person.php#L352)) should use core `get_password_reset_key()` ([link](https://developer.wordpress.org/reference/functions/get_password_reset_key/))

**Comment by eri-trabiccolo** [comment]
@thomas 
why don't we just deprecate `llms_set_user_password_rest_key()`,`llms_verify_password_reset_key()` (which actually is called `llms_verify_password_rest_key()` which is a good reason to deprecate it :P) and use the wp core functions?
Also considering that our `llms_verify_password_rest_key()` doesn't completely "match" `get_password_reset_key()`. In fact, the wp function includes a piece of code we've put here:
https://github.com/gocodebox/lifterlms/blob/3.36.4/includes/forms/controllers/class.llms.controller.account.php#L163-L182

there also this other function here:
https://github.com/gocodebox/lifterlms/blob/3.36.4/includes/forms/frontend/class.llms.frontend.password.php#L29
that's a little bit different, although it doesn't seem to be used anymore.



From a rapid search couldn't find any addons using `llms_verify_password_reset_key()` and `llms_set_user_password_rest_key()`.

**Comment by thomasplevy** [comment]
@eri-trabiccolo agreed, still low priority though. I welcome arguments and PRs from those affected. I'd prefer not to use internal resources on this at this moment, we have a lot of more pressing issues to resolve.

**Comment by thomasplevy** [comment]
This is resolved on the customize branch and will be included in a future version of LifterLMS
