### ISSUE TITLE
nginx - upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by badpenguin** [gocodebox/lifterlms#889]
### Reproduction Steps

From the WP users's list i'm trying to enroll 72 users to a course.

On Nginx it generates a 502 bad gateway response and in the webserver's logs i see the following message:
```
upstream sent too big header while reading response header from upstream
```

The fix is to raise the fastcgi buffer sizes:
```
fastcgi_buffer_size 32k;
```

I think you should consider adding this suggestion to the documentation or probably rewrite the mass enroll features to use a POST request instead of a GET request - in my case the URL was longer more then 2000 chars.

**Comment by thomasplevy** [comment]
Thanks for the feedback.

Since the default users list is 20 users per page this is one of those (assumed) known issues, like, for example, if you were to change the list to 10000 it would *allow you to do so* but would likely result in timeouts from the server.

I took a look at the suggestion of switching to `POST` instead of `GET` for the form submission however the user table is wrapped in a form with a `GET` method. This comes from the WordPress core. This means that all the bulk actions (default from the core or custom from plugins) will have to also use `GET` methods for the form submission.

Your suggestion to increase the buffer size seems reasonable. I've noted this on our documentation task list and will find a place to add this into our knowledgebase in the future.

Thanks
