### ISSUE TITLE
Auto creation of pages overwrites existing site pages

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#914]
### The problem
During the setup of LifterLMS there is the option to have the LifterLMS pages installed. If a page with the same name exists on the site Lifter will overwrite this page.

### Expected Behavior
If a page with the same name exists for instance courses then LifterLMS will automatically create a courses-2 page and use that for the LifterLMS Course Catalog. The user can then rename the page.

**Comment by thomasplevy** [comment]
This is intentional behavior.

We attempt to identify if the page already exists by slug, existing options already saved to the database, pages that already exist with differing names that have the expected content (eg: the student dashboard should have the `[lifterlms_my_account]` shortcode, etc...

Since the setup wizard can be rerun an infinite number of times we attempt to update -- instead of creating new pages -- so that we reduce potential clutter.

**Comment by paaljoachim** [comment]
I just know that I had some problems with LifterLMS taking over a course page. So on the live site I decided not to use the wizard and instead manually create the pages.
